- README.md
> Updated README.md with information on docker image and environment

- api/dotnet/README.md
- api/dotnet/Services/MongoService.cs
- openshift/jenkins/api/Jenkinsfile
- openshift/templates/api/dotnet/README.md
- openshift/templates/api/dotnet/build.yaml
- openshift/templates/api/dotnet/deploy.yaml
- openshift/templates/base-images/README.md
- openshift/templates/base-images/mongodb.yaml
- openshift/templates/db/mongo/README.md
- openshift/templates/db/mongo/deploy.yaml
- openshift/templates/network/network-security-policy.yaml
- openshift/templates/pipeline/api-pipeline.yaml
Getting OpenShift to work with this project.
Adding templates for CI/CD.
> DevOps OpenShift Integration

- api/dotnet/Controllers/DmerController.cs
- api/dotnet/Helpers/Json/JsonParser.cs
- api/dotnet/Models/Dmer.cs
- api/dotnet/Services/MongoService.cs
- api/dotnet/Startup.cs
- api/dotnet/Views/Dmer/QueueTable.cshtml
- api/dotnet/wwwroot/css/tables.css
New endpoint /api/queue/dmer/table to view a prettier output of the queue.
Fixed endpoint /api/queue/dmer/processed to fix status issue.
> Fixing PUT.  Adding table endpoint.

- openshift/templates/README.md
This will help you get started with OpenShift and provides some information on how things are currently working.
> OpenShift documentation

- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
> Added placeholder comment for search box

- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
S3DMFT-2306: Added Expansion panel to show DMER Definitions and header changes on Dashboard
> S3DMFT-2306: Added Expansion panel to show DMER Definitions and header changes on Dashboard

- medical-portal/src/UI/medical-portal/src/app/app-routing.module.ts
- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.html
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.scss
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.ts
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/styles.scss
1. Added Case Id Assistance Component
2. Added routing to navigate from dashboard to Assistance page
> S3DMFT-2915 - DMER Case Id Assistance page

- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/medical-portal/src/app/layout/nav-menu/nav-menu.component.html
- Fixed Dashboard Element Spacing
- Fixed Search DMER Case ID Changes
- Fixed DMER Definition Collapsible changes
- Fixed Changes on DMER Table
>  S3DMFT-2306 - Dashboard Changes based on the feedback

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CommentsController.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/DpsController.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/DriversController.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Startup.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/ViewModels/Document.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/LegacyAdapterTest.cs
S3DMFT-2923 Support for submit document with no url
> S3DMFT-2923 Automated testing for submit document

- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/medical-portal/src/app/layout/footer/footer.component.html
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/clinic-user-profile.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/dmer-case-list-item.ts
- medical-portal/src/UI/medical-portal/src/styles.scss
- Added new columns DMER Type and Driver DOB fields to cases table
- Added functionality for filtering and sorting 
- Updated Footer Copyright Content
> S3DMFT-2803 - Changes to DMER case Table

- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
- Added functionality to show different buttons based on the case status
- Added navigation to go to cases page when you start or continue DMER.
> S#DMFT - Search DMER Case Id

- medical-portal/src/UI/medical-portal/angular.json
- medical-portal/src/UI/medical-portal/package-lock.json
- medical-portal/src/UI/medical-portal/package.json
- medical-portal/src/UI/medical-portal/src/app/app-routing.module.ts
- medical-portal/src/UI/medical-portal/src/app/app.component.ts
- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.html
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.ts
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/medical-portal/src/app/shared/services/case-management/case-management.service.ts
- medical-portal/src/UI/medical-portal/src/styles.scss
- Created DMER case Details page to show DMER information and further information
- Added ng busy loading component to dashboard 
-
> S3DMFT- 3012 Create DMER Case Details Page

- medical-portal/src/UI/medical-portal/src/app/app-routing.module.ts
- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/layout/header/header.component.html
- medical-portal/src/UI/medical-portal/src/app/shared/api/models.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/email-update.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/practitioner-bridge.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/provider-role.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/user-profile.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/request-builder.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/services/config.service.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/services/profile.service.ts
- medical-portal/src/UI/medical-portal/src/app/shared/services/profile.service.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Added Component for user profile
- Added Component for Edit User Profile Dialog 
- Added User Service
> S3DMFT - View and Manage MOA profile

- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Added sorting functionality to Medical Association Table
- Added manage/delete dialog to remove Medical Association
> SEDMFT- 2797 - Manage Associations to Medical Portal

- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-staff-association-dialog/create-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-staff-association-dialog/create-medical-staff-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-staff-association-dialog/create-medical-staff-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-staff-association-dialog/create-medical-staff-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-staff-association-dialog/edit-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-staff-association-dialog/edit-medical-staff-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-staff-association-dialog/edit-medical-staff-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-staff-association-dialog/edit-medical-staff-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-staff-association-dialog/manage-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-staff-association-dialog/manage-medical-staff-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-staff-association-dialog/manage-medical-staff-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-staff-association-dialog/manage-medical-staff-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Added table to show medical staff association
- Added Component to create medical staff association
- Added component to edit medical staff association
- Added component to manage/edit medical staff association
- Updated Dialog header styles
> S3DMFT-2799 Manage Associations with Medical Staff Practitioners

- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-association-dialog/create-medical-practitioner-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-role-association-dialog/create-medical-practitioner-role-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-role-association-dialog/create-medical-practitioner-role-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-role-association-dialog/create-medical-practitioner-role-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-role-association-dialog/create-medical-practitioner-role-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-role-association-dialog/edit-medical-practitioner-role-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-role-association-dialog/edit-medical-practitioner-role-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-role-association-dialog/edit-medical-practitioner-role-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-role-association-dialog/edit-medical-practitioner-role-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-user-profile-dialog/edit-medical-practitioner-user-profile-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-user-profile-dialog/edit-medical-practitioner-user-profile-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-user-profile-dialog/edit-medical-practitioner-user-profile-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-user-profile-dialog/edit-medical-practitioner-user-profile-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-role-association-dialog/manage-medical-practitioner-role-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-role-association-dialog/manage-medical-practitioner-role-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-role-association-dialog/manage-medical-practitioner-role-association-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-role-association-dialog/manage-medical-practitioner-role-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-staff-association-dialog/manage-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
-Added Edit Medical Practitioner User Profile Dialog Component
-Added Create Medical Practitioner Role Association Dialog Component 
-Added Edit Medical Practitioner Role Association Dialog Component
- Added Manage Medical Practitioner Role Association Dialog Component
- Added multi select functionality to Medical Practitioner role Association table
> S3DMFT - 2801 - Manage associations for medical Practitioners

- medical-portal/src/UI/medical-portal/src/app/shared/components/phsa-form-viewer/phsa-form-viewer.component.scss
- Added Styles to take adjust height and width of the iframe.
> S3DMFT-812 – Adjusted the HTML of the iframes so it more closely matches the Wireframes.

- medical-portal/src/UI/medical-portal/src/app/shared/api/models/clinic-user-profile.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/models/provider-role.ts
- medical-portal/src/UI/medical-portal/src/app/shared/api/services/profile.service.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Added functionality to show respective UI based on the user Profile for Medical Practitioner, MOA and MOM Profiles
> S3DMFT # 2801 Manage associations for medical Practitioners

- medical-portal/src/UI/medical-portal/src/app/shared/services/profile.service.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-user-profile-dialog/edit-medical-practitioner-user-profile-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-medical-practitioner-user-profile-dialog/edit-medical-practitioner-user-profile-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Updated Edit Medical Practitioner user profile to show data
- Updated Test data for Medical Practitioner, MOM, MOA tables
> S3DMFT # 2802 View and manage Medical Practitioner user profile 

- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Added sorting functionality for medical practitioner roles table
> S3DMFT # 2801 Manage associations for medical Practitioners  

- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.html
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/layout/header/header.component.html
- medical-portal/src/UI/medical-portal/src/app/layout/header/header.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-role-association-dialog/create-medical-practitioner-role-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-practitioner-role-association-dialog/create-medical-practitioner-role-association-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
Changes to dashboard and profile page based on the feedback
- Updated Case Assistance page
- Updated Dashboard page - Title, DMER Definitions, Navigation issues 
- Updated User profile page based on the feedback
> S3DMFT # Changes to dashboard and profile page based on the feedback

- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-staff-association-dialog/create-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/create-medical-staff-association-dialog/create-medical-staff-association-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-association-dialog/manage-medical-practitioner-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-practitioner-role-association-dialog/manage-medical-practitioner-role-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/manage-medical-staff-association-dialog/manage-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/remove-medical-staff-association-dialog/remove-medical-staff-association-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- Updated Mat header, button styles to align with the wireframes
- Updated MOM and Medical Practitioner bulk status
- Fixed the scrolling issue on Edit, Create Medical Practitioner Roles Dialog
- Fixed content on Medical staff association and Medical Practitioner dialog for the remove action
> S3DMFT # 2801 Changes to Medical Practitioner User Profile based on the feedback

- medical-portal/src/UI/medical-portal/src/_theme.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/edit-user-profile-dialog/edit-user-profile-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.html
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.scss
- medical-portal/src/UI/medical-portal/src/app/user-profile/user-profile.component.ts
- medical-portal/src/UI/medical-portal/src/index.html
- medical-portal/src/UI/medical-portal/src/styles.scss
- Updated All fonts to match BC Sans family
- Fixed mat input fields to show border
- Fixed the styles for text on card content
- Fixed sorting default functionality on all user profile tables
- Added styles to show different colors to the status
> S3DMFT # 2802 Changes to Medical Practitioner User Profile based on the feedback

- medical-portal/src/UI/medical-portal/package-lock.json
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.html
- medical-portal/src/UI/medical-portal/src/app/case-assistance/case-assistance.component.scss
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.html
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
S3DMFT#3547  Medical Portal: Dashboard changes 
Updated UI changes on dashboard based on the latest changes
S3DMFT # 3549 Medical Portal: DMER Case ID Help changes
Updated UI changes on DMER Case Id page based on the latest changes
S3DMFT# 3562 Medical Portal: DMER Table row adjustments
Added row click functionality to navigate to case or case detils page
S3DMFT# 3548 Medical Portal: DMER Case Details changes
Updated UI changes on DEMER Case Details Page based on the latest chages
> Medical Portal Dashboard Changes

- medical-portal/src/UI/medical-portal/src/app/app-routing.module.ts
- medical-portal/src/UI/medical-portal/src/app/app.module.ts
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.html
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation-dialog/dmer-submission-confirmation-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation-dialog/dmer-submission-confirmation-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation-dialog/dmer-submission-confirmation-dialog.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation-dialog/dmer-submission-confirmation-dialog.component.ts
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation.component.html
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation.component.scss
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation.component.spec.ts
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation.component.ts
- Added new component for dmer submission confirmation page
- Updated UI on the dmer submission page
- Added the report  a condition alert toolbar on case details page
> S3DMFT# 3550 Medical Portal: Thank you for your submission changes

- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.html
- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.ts
S3DMFT# 3497 - Medical Portal Dashboard Changes
- Updated DMER type border colors based on the latest feedback
S3DMFT # 3496 Medical Portal: DMER Case Details changes
- Updated Case details page based on the latest feedback
> Medical portal changes for dashboard and Case etails page

- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.html
Updated Case details page based on the latest feedback
> S3DMFT # 3496 Medical Portal: DMER Case Details changes

- medical-portal/src/UI/medical-portal/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/medical-portal/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation-dialog/dmer-submission-confirmation-dialog.component.html
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation-dialog/dmer-submission-confirmation-dialog.component.scss
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation.component.html
- medical-portal/src/UI/medical-portal/src/app/dmer-submission-confirmation/dmer-submission-confirmation.component.scss
S3DMFT # 3496 Medical Portal: Pop up window feature
Updated UI changes on DMER submission confirmation dialog based on the latest feedback
S3DMFT # 3550 Medical portal : DMER Thank you for your submission page
Updated UI on DMER thankyou confirmation page based on the latest feedback
> Medical Portal changes for Thank you submission page and the confirmation Dialog 

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
S3DMFT # 3747 Error Visibility for Scheduled Jobs
- Added GRPC request and response for BringForward
- Added the CreateBringForward to both case manager and Service layer
- Added unit tests to test the CreateBringForward method to add bring forward for a driver
> S3DMFT # 3747 Error Visibility for Scheduled Jobs

- landing-page/src/html/index.html
- Changed the modal poup close button
> S3DMFT # 3797 # Medical Portal Public Landing Page - Javascript implementation

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Rsbc.Dmf.CaseManagement.Tests.csproj
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/FlatFileUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Protos/icbcAdapter.proto
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Services/IcbcAdapterService.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/EnhancedApiTest.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/FlatFileTest.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/IcbcLoadTest.cs
- scheduler/src/Pssg.Dmf.Scheduler/Pssg.Dmf.Scheduler.csproj
- scheduler/src/Pssg.Dmf.Scheduler/ScheduledJobs.cs
- scheduler/src/Pssg.Dmf.Scheduler/Startup.cs
-  Adding new GRPC  call to the ICBC Adapter
> S3DMFT# 3754 Resolve case if DPS processing Date has passed the case resolve date

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/DriverHistoryController.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/Address.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/ClientDetails.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/DriverDetails.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/ExpandedStatuses.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/IcbcClient.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/Medicals.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/Name.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/IcbcModels/Restrictions.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/EnhancedApiTest.cs
S3DMFT # 3828 Support for new ICBC Tombstone enhancement
- Added models for mapping ICBC tombstone data
- Updated the Driverhistory controller to use the enhancedICBC utils insted of ICBC Client
- Added a function to map the GetDriver history in JSON Format
S3DMFT# 3754 - Added Unit test to Resolve case in dynamics
> S3DMFT # 3828 Support for new ICBC Tombstone enhancement

- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Rsbc.Dmf.LegacyAdapter.csproj
- Added feature flag to case controller
- Updated nuget package for Google protobuf package
> S3DMFT # 4021 Feature Flag to control if files are processed from DPS

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Rsbc.Dmf.BcMailAdapter.csproj
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Startup.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/ViewModels/Attachment.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/ViewModels/BcMail.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/ViewModels/LetterGenerationRequestModel.cs
- Added Document contoller and added preview post method
- Added a method to get the token and autenicate to CDGS Service
- Added View models for the documents
> S3DMFT # 3806 BC Mail Requirements

- bcmail-adapter/openshift/templates/bcmail-adapter.template.yml
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- bcmail-adapter/src/Rsbc.Interfaces.Dmf.BcMailAdapter/PdfResponse.cs
- bcmail-adapter/src/Rsbc.Interfaces.Dmf.BcMailAdapter/StreamExtensions.cs
Updated the PDF Preview functionality to accept base64 encoded response
> S3DMFT# 4020  BC Mail service development in OpenShift

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Rsbc.Dmf.BcMailAdapter.csproj
S3DMFT #4421 Add Merge functionality to combine the documents into one pdf
- Added PDF Sharp nuget package 
- Updated the Preview Post Method to Support multiple documents to be merged in the Preview
> S3DMFT #4421 Add Merge functionality to combine the documents into one pdf

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/CreateDocumentUtils.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Rsbc.Dmf.BcMailAdapter.csproj
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/ViewModels/Attachment.cs
- bcmail-adapter/src/Rsbc.Interfaces.Dmf.BcMailAdapter/CdgsModels/Template.cs
- bcmail-adapter/src/Rsbc.Interfaces.Dmf.BcMailAdapter/CdgsServiceClient.csproj
- bcmail-adapter/src/Rsbc.Unit.Tests.Dmf.BcMailAdapter/CdgsClientTest.cs
- bcmail-adapter/src/Rsbc.Unit.Tests.Dmf.BcMailAdapter/CreateDocumentTest.cs
Added create document us class to add headers and footers
Added Test class for testing the Create Document
> S3DMFT # 4429 Adding Headers and footer to the letter generation document

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Controllers/FileController.cs
- document-storage-adapter/src/Pssg.DocumentStorageAdapter/DocumentConvertUtil.cs
- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Pssg.DocumentStorageAdapter.csproj
- document-storage-adapter/src/Pssg.Unit.Tests.Interfaces.S3/DocumentConvertUtilTest.cs
- document-storage-adapter/src/Pssg.Unit.Tests.Interfaces.S3/DynamicsInterfaceTest.cs
-  Added a feature flag to verift the tiff document type
- Updated the Document end point to convert tiff to pdf -Added Document Convert Util file
- Added unit tests for testing tiff to pdf conversion
> S3DMFT # 3740 Convert TIFF to PDF in Mercury

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Protos/icbcAdapter.proto
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Services/IcbcAdapterService.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Startup.cs
- icbc-adapter/src/Pssg.Interfaces.Icbc/EnhancedIcbcClient.cs
- scheduler/src/Pssg.Dmf.Scheduler/ScheduledJobs.cs
- scheduler/src/Pssg.Dmf.Scheduler/Startup.cs
-[Scheduler]Added a HangFire Job to update Birthdate in Scheduler Project
- [ICBC Adapter]Added GRPC call to UpdateBirthDate to ICBC Adapter
- Added the UpdateBirthdate to EnhancedICBC Uils which will get the list of drivers and compare the DOB from ICBC and Dynamics
- [CMS Adapter]Added the GRPC call to update the DOB in CMS adpter
- Added DOB to get drivers method
- Added Test to Update DOB
> S3DMFT# 4295 Mismatch in DOB for DL# in dynamics and ICBC

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- scheduler/openshift/templates/scheduler-adapter.template.yml
-  Added a unit test in case manager to set the clean pass to true.
> S3DMFT# 4013 Review and confirm Clean Pass functionality

- .github/workflows/cd-scheduler-service.yml
- .github/workflows/ci-scheduler-service.yml
- scheduler/openshift/README.md
- scheduler/openshift/templates/scheduler-service.template.yml
- scheduler/src/Dockerfile
- Renamed the openshift objects to scheduler-service
- Added CI/CD workflows for scheduler service project
- Updated docker file run command
> S3DMFT# 4498 DevOps required for Scheduler Service

- bcmail-adapter/openshift/templates/bcmail-adapter.template.yml
- scheduler/openshift/templates/scheduler-service.template.yml
- Added Service certificate annotations for both bc mail and scheduler openshift templates
> S3DMFT # 4498 DevOps required for Scheduler Service

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
S3DMFT # 3208 DPS Action: Assign Document Priority
- Updated CreateLegacyCaseDocuments with the Document priority type
> S3DMFT # 3208 DPS Action: Assign Document Priority

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Protos/bcmailAdapter.proto
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Rsbc.Dmf.BcMailAdapter.csproj
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Services/BcMailService.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/SfegUtils.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
DPS Action: Assign Queue
- Updated logic in the Casemanger to add owner to a document
S3DMFT #3808  Hangfire Process - Send to BCMail
- Updated the PdfDocuments to get list of pdf documents
- Updated the UpdateDocument status to update the status when send to BC mail
- Updated SFEGutils file in BC mail adapter
- Added unit tests to get list of documents
> S3DMFT # 3207 DPS Action: Assign Queue and Priority

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
S3DMFT # 4295 Mismatch in DOB for DL# in dynamics and ICBC
- Updated  Startup file Scheduler project
S3DMFT # 4595 TEST ENVIRONMENT - Clean pass document processed in DPS showing up in Mercury as unsolicited DMER
- Updated Clean pass logic to set the document status and clean pass flag
> S3DMFT # 4295 Mismatch in DOB for DL# in dynamics and ICBC - Updated  Startup file Scheduler project

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
S3DMFT # 3206 DPS Action: Accept/Reject Document
- Updated CMS proto file to add the submittal status 
- Added logic to create case documents to update the document status when send from DPS
- Added unit tests to test the Accept reject status
> S3DMFT # 3206 DPS Action: Accept/Reject Document

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
Updated Reject status logic to create a new document type
> S3DMFT # 3206 DPS Action: Accept/Reject Document 

- bcmail-adapter/openshift/templates/bcmail-adapter.template.yml
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- Updated Lookup owner function to set the validation previous value
- Adjusted the BC mail Openshift manifest file
> S3DMFT# 4607 No Bring forward to me was created when a document is sent from DPS with a queue: "Bring Forward to Me"

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Rsbc.Dmf.BcMailAdapter.csproj
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Services/BcMailService.cs
- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Startup.cs
- bcmail-adapter/src/Rsbc.Unit.Tests.Dmf.BcMailAdapter/SfegUtilsTest.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- openshift/deploy-test.bat
- scheduler/src/Rsbc.Dmf.Scheduler/ScheduledJobs.cs
- Updated BCMAil service to include the Token method
- Updated and added missing GRPC calls
- Adjusted BC mail start up file to add missing GRPC calls
[Scheduler] - Adjusted scheduler jobs file to include BC mail Configuration
- Updated openshft test deploy batch file to include bcmail and scheduler projects
> S3DMFT# 3808  Hangfire Process - Send to BCMail

- README.md
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
Updated Send to BCMail and Resolve Case Status hangfire job to run daily
- Updated Hangfire documentation in Readme file
> Updated Send to BCMail and Resolve Case Status hangfire job to run daily

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- scheduler/src/Rsbc.Dmf.Scheduler/ScheduledJobs.cs
Added Missing Configuration for the CMS adapter in scheduler project
Added null check for the clean pass method
> Added Missing Configuration for the CMS adapter in scheduler project

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
- scheduler/src/Rsbc.Dmf.Scheduler/ScheduledJobs.cs
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
- Modified the UpdateNonComplyDocuments to update only the submittalstatus filed.
- Added GRPC call for UpdateNonComplyDocuments
- Added UpdateNonComplyDocuments hangfire job to scheduler project
> S3DMFT#4685 Non comply document - Hangfire Process

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- scheduler/src/Rsbc.Dmf.Scheduler/ScheduledJobs.cs
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
- Updated clean pass logic to use the updated patch method
- Added  feature flag for AddCaseDocument
- Deleted the Clean pass hangfire job from scheduler
> DMFT# 4689 Clean Pass - Hangfire Instant Trigger

- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
- Added integration tests to test the sur codes for different scenarios
> DFTHG#31 DPS is not able to validate driver with surname with single character

- .github/workflows/cd-driver-portal-api.yml
- .github/workflows/ci-driver-portal-api.yml
- driver-portal/src/Controllers/ApplicationVersionInfoController.cs
- driver-portal/src/Dockerfile
- driver-portal/src/Models/ApplicationVersionInfo.cs
- driver-portal/src/driver-portal.csproj
- Updated CI/CD workflows for the driver portal
- Updated docker file to include the build versions
- Added ApplicationVersionInfo controller
> DFTHG# 87 Create OpenShift Manifests for Driver Portal

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Services/IcbcAdapterService.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Startup.cs
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
- Updated SendMedicalUpdates to remove the hangfirecontext
- Added timeout for the ICBC and CMS httpClients
- Added a unit tet to test GetUnsentMedicalUpdates method
> DFTHG # 170 Medical Disposition Update - Dynamics

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/ICaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/CaseUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/IcbcController.cs
- Added Create Bring forward, Create Case comments functionality for ICBC medical Candidate creation
- Added CreateICBCMedicalCandidateComment function to CMS adapter
> DFTHG# 293 Auto create comments for Medical Candidate Received - Existing Case 

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/IcbcController.cs
- Adjusted Date of Issuance and auto comments queue for the comments
> DFTHF # 292 Auto create comments for Medical Candidate Received - No Existing Case 

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/IcbcController.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/DriversController.cs
Added the issue date to populate the compliance date on the documents
> DFTHG-155 Medical Candidate - Openshift (No Open Case) and Existing Cases

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- Aded logic to set the DPSR to manual pass
> DFTHG# 350 DMER Manual Pass- Document Owner: DPSer ID

- bcmail-adapter/openshift/templates/bcmail-adapter.template.yml
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Moq/CmsHelper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseServiceTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/ICaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/FlatFileUtils.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/EnhancedApiTest.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/FlatFileTest.cs
-Updated BCmail template with SCP settings
> DFTHG# 355 Verify the SFEG Credentials and Configure hangfire job to send letters to BCMail

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
-Updated File name for the files that are sent to BCMail
> DFTHG-355 - Fully implement SFTP for BCMail

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- Adjusted the CaseType codes for caseTitle
- Adjusted the medical disposition logic to check for "P" status exsists
- Adjusted the BCmail file name
> DMFHG#  355 Fully implement SFTP for BCMail 

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
Updated the pdfdocument and driverlink for bcmail documents
> DFTHG# 395 Generated Letters result in Documents that are missing Driver Link

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/ICaseManager.cs
- Updated the fine name for bcmail pdf documents
- Added clean pass logic to add the DPSR when its a clean pass
- Added CreateDocumentOnDriver method for attaching documents to driver
> DFTHG# 447 DPS Mitigation - Architecture - Driver / Case Validation - Driver Creation

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- Updated combine PDF logic to add a blank page if the pdf document has odd number of pages
> DFTHG# 516  Adding White Pages to Odd Paged Document Attachments

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Connected Services/Dynamics/DynamicsCsdl.xml
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
- Updated add document method with all the list of cases for the remedial cases in the case controller
- Added unit tests for testing the the remedial cases
> DFTHG # 479 DPS Mitigation - Architecture - Driver / Case Validation - Remedial Documents

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
- Added functionality to attach the document to driver and don't set the case 
- Added Dfp Queue Field  to the case Controller and case manager
> DFTHG # 549 DPS Mitigation - Don't set Case on new documents

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- Updated CreateDocumentonDriver to create a driver and person record
> DFTHG # 525  Person Record is not created for a document received through DPS and the Driver record is present in ICBC but not in Mercury

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/DpsAddDocumentTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
- Added logic for adding envelope for create case on driver
- Added unit tests to test the envelope creation
> DFTHG # 553 Document processed through Mercury is not filling the document envelope

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/wwwroot/splitter.html
- Added basic UI for the document splitter
> DFTHG # 585 Basic UI for document splitter

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/wwwroot/splitter.html
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
DFTHG # 582 Remedial Documents are coming to Mercury in uploaded status
- Fixed the issue with remedial case documents
DFTHG # 550 DPS Mitigation - Use Calendar Date to calculate case closure
- Updated the case closure method to use the current date for closing the case
> DFTHG # 582 Remedial Documents are coming to Mercury in uploaded status

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/wwwroot/splitter.html
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- Added function to call the document spllit end point and split the document
>  DFTHG # 585 Basic UI for document splitting functionality

- cms-adapter/src/Rsbc.Dmf.CaseManagement/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Connected Services/Dynamics/DynamicsCsdl.xml
Adjusted case manager code to use the new dps process date
> DFTHG # 518 DPS Processing Date - New Calculation

- driver-portal/src/ClientApp/src/app/app-routing.module.ts
- driver-portal/src/ClientApp/src/app/app.module.ts
- driver-portal/src/ClientApp/src/app/case/case.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.spec.ts
- driver-portal/src/ClientApp/src/app/case/case.component.ts
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.html
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.html
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.scss
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.spec.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- driver-portal/src/ClientApp/src/app/shared/api/fn/cases/api-cases-most-recent-get-json.ts
- driver-portal/src/ClientApp/src/app/shared/api/fn/cases/api-cases-most-recent-get-plain.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/case-detail.ts
- driver-portal/src/ClientApp/src/app/shared/api/services/cases.service.ts
- driver-portal/src/ClientApp/src/app/shared/services/case-management/case-management.service.ts
- driver-portal/src/ClientApp/src/styles.css
- driver-portal/src/Controllers/CasesController.cs
- shared-portal-ui/projects/core-ui/src/lib/layout/footer/footer.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
- Added RecentCaseDetail Component
- Added cases component
- Added and generated the get recent case api end point.
- Added the shared RecentCaseDetail in case and sashboard pages
- Updated styles on the dashboard page.
> DFTDP # 96 UI Development for Dashboard

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/WebAppTestBase.cs
fix for case manager tests, it was loading the wrong startup
> DFTDP-97 fix for case manager tests

- driver-portal/src/Tests/coverlet.runsettings
add coverlet file for code coverage
> DFTDP-89 add coverlet file

- driver-portal/src/ClientApp/src/app/account/account.component.html
- driver-portal/src/ClientApp/src/app/app.module.ts
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.html
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.css
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.html
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.spec.ts
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.spec.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.ts
- driver-portal/src/ClientApp/src/app/quick-links/quick-links.component.css
- driver-portal/src/ClientApp/src/app/quick-links/quick-links.component.html
- driver-portal/src/ClientApp/src/app/quick-links/quick-links.component.spec.ts
- driver-portal/src/ClientApp/src/app/quick-links/quick-links.component.ts
- driver-portal/src/ClientApp/src/app/shared/services/case-management/case-management.service.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.css
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.spec.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- driver-portal/src/Controllers/CasesController.cs
- driver-portal/src/Controllers/DriversController.cs
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
- Added quick links component to use on multiple case details page
- Updated case submissions tab
- Updated submission requirements tab
-  Updated Account details page to remove ICBC identification
> DFTDP # 104 UI Development for case details page

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/Enum/ActiveStatus.cs
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.ts
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.css
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.scss
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.html
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.scss
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.html
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.scss
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- Added logic foe closed case weeks.
- Changes for the case manager to get the documents
> DFTDP # 103 Implement UI for closed cases

- driver-portal/src/ClientApp/src/app/case-details/case-details.component.html
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.spec.ts
Fix the Angular unit test that was blocking the driver-portal-ui CI build
> DFTDP-109 fix unit test that is blocking build

- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.css
- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.ts
- shared-portal-ui/projects/core-ui/src/lib/layout/layout.module.ts
- Added the account button to the header to navigate to account page
- Added functionality to logout.
> DFTHG # 96 UI Development for Dashboard.

- driver-portal/src/ClientApp/src/app/case-details/case-details.component.html
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.ts
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.css
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.html
- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- Added logic to navigate view letter button to letters to driver tab
- Updated logic on the case submissions expansion 
- Updated styles on the case details expansion
> DFTHG# 104 UI Development for case details page.

- driver-portal/src/ClientApp/src/app/app-routing.module.ts
- driver-portal/src/ClientApp/src/app/app.module.ts
- driver-portal/src/ClientApp/src/app/letter-details/letter-details.component.html
- driver-portal/src/ClientApp/src/app/letter-details/letter-details.component.spec.ts
- driver-portal/src/ClientApp/src/app/letter-details/letter-details.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- Added letters details components to show the letter to drivers
- Updated routing to usr the letterdetails component
> DFTDP # 87 Driver Portal - Document History

- driver-portal/src/ClientApp/src/app/case-submissions/case-submissions.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.scss
- driver-portal/src/ClientApp/src/app/case/case.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.css
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.ts
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.html
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/styles.css
- driver-portal/src/Program.cs
Updated pagination on letters to drivers and submission history tab to show 10 documents per page.
- Updated styles.css with new pagination styles
> Dmf driver portal

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/UserService.cs
- driver-portal/src/Controllers/ProfileController.cs
Fix issue with driver id being passed in from frontend oauth to the backend claims
> DFTDP-115 fix driver id

- driver-portal/src/ClientApp/src/app/app.component.html
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.ts
- driver-portal/src/ClientApp/src/app/case/case.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.ts
- driver-portal/src/ClientApp/src/app/letter-details/letter-details.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.css
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.html
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.scss
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/user-profile.ts
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.css
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.html
- driver-portal/src/ClientApp/src/styles.css
- Added functionality to show the case status for the most recent case
_ adjusted styling on the submission history page
- Adjusted case Id on dashboard and closed cases
- Added fixed header and navigation bar
> DFTP# 76 Dashboard - Track Status of Case

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/UserManagerTests.cs
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.ts
- driver-portal/src/Controllers/ApplicationVersionInfoController.cs
- driver-portal/src/Controllers/CasesController.cs
Remove get case by id service, since it is no longer needed.
Add authorize driver policy to get most recent case service, which was forgotten in last PR for 113
Code cleanup
> DFTDP-119 remove get case by id service

- driver-portal/src/ClientApp/proxy.conf.js
- driver-portal/src/ClientApp/src/app/app-routing.module.ts
- driver-portal/src/ClientApp/src/app/app.component.html
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.html
DFTDP # 121 Updates to driver portal pages based on the latest feedback and wireframes
- Adjusted Up on the case details page to show only case submissions
- Updated proxy config file
- Added navigation to view letter button to navigate to letter to drivers page
> DFTDP # 121 Updates to driver portal pages based on the latest feedback and wireframes

- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.css
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- Added document upload functionality to case details page.
- Added styles to the document upload component.
> DFTDP# 86 Driver Portal - Document Upload

- driver-portal/src/ClientApp/src/app/account/account.component.html
- driver-portal/src/ClientApp/src/app/account/account.component.scss
- driver-portal/src/ClientApp/src/app/account/account.component.ts
- driver-portal/src/ClientApp/src/app/app-routing.module.ts
- driver-portal/src/ClientApp/src/app/app.module.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.spec.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/quick-links/quick-links.component.html
- driver-portal/src/ClientApp/src/app/shared/api/fn/profile/api-profile-driver-put.ts
- driver-portal/src/ClientApp/src/app/shared/api/models.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/driver-update.ts
- driver-portal/src/ClientApp/src/app/shared/api/services/profile.service.ts
- driver-portal/src/ClientApp/src/app/shared/material.module.ts
- driver-portal/src/ClientApp/src/app/shared/services/case-management/case-management.service.ts
- driver-portal/src/ClientApp/src/app/user-registration/user-registration.component.html
- driver-portal/src/ClientApp/src/app/user-registration/user-registration.component.scss
- driver-portal/src/ClientApp/src/app/user-registration/user-registration.component.ts
- driver-portal/src/ClientApp/src/styles.scss
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.scss
DFTDP# 66 Account Creation
- Updated editable feilds on account and user registration page
DFTDP# 118 UI Development for Driver Request Call back page
- Added new component for get assistance page
- updated navigation bar to add get assistance page
> DFTDP# 66 Account Creation

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- driver-portal/src/Controllers/DocumentController.cs
- driver-portal/src/Model/DocumentUtils.cs
- driver-portal/src/Tests/Integration/DocumentTests.cs
Fix the integration test to add the file contents correctly and then was able to add the mimetype check back
Fixed a bug to not detach owner if there was no owner found. Not sure what the owner or "ValidationPrevious" properties should be which would populate the owner
> DFTDP-123 test mime type

- driver-portal/src/ClientApp/src/app/account/account.component.ts
- driver-portal/src/ClientApp/src/app/app.component.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.scss
- Added help tops on the get assistance page
- Added request call back card on the get assistance page
> DFTDP#118 UI Development for Driver Request Call back page

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- driver-portal/src/Controllers/DriverController.cs
- Fixed the issue to show letter to drivers
> DFTDP # 88 Driver Portal - Document Submission

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/shared/api/models/document.ts
- driver-portal/src/Controllers/DocumentController.cs
- driver-portal/src/ViewModels/Document.cs
Fix case type, case id, and submission type.
Description and due date are still outstanding, need more requirements.
> DFTDP-92 fix for case type, case id, and submission type

- driver-portal/src/ClientApp/src/app/app.component.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.html
- Added Call back request button functionality
- Added card to show request call back history
- Updated Get assistance path on mobile view
> DFTDP # 118 UI Development for Driver Request Call back page

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/DriverHistoryController.cs
- icbc-adapter/src/Pssg.Interfaces.Icbc/ViewModels/Driver.cs
> DFTHG # 880 Building Unit Number isn't populating in Letters

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/DriverHistoryController.cs
Updated changes for manual pass in CMS adapter
DFTHG # 910
PO Box being inserted into the middle of the Street Address 
- Updated POBOX address  issue to show that to bottom of the address line
> DFTHG-857 Medical Disposition Update - Changes for Manual Pass

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
DFTHG # 889 Attached adjudicative documents are being printed a different size
Updated combine pdf code to resize the page size.
DFTHG # 890 Documents for Printed vs. Faxed are coming out as different sizes
> DFTHG # 889 Attached adjudicative documents are being printed a different size

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/DriverHistoryController.cs
Updated POBOX address  issue to show that to bottom of the address line
> DFTHG # 910 PO Box being inserted into the middle of the Street Address

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
- Adjusted the code to check for case status
- Adjusted ResolveCaseStatus job to run after other jobs
> DFTHG # 922 Automatic case closure while file under review

- driver-portal/src/ClientApp/src/app/app.module.ts
- driver-portal/src/ClientApp/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.spec.ts
- driver-portal/src/ClientApp/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/shared/api/api.module.ts
- driver-portal/src/ClientApp/src/app/shared/api/fn/callback/api-callback-driver-get-json.ts
- driver-portal/src/ClientApp/src/app/shared/api/fn/callback/api-callback-driver-get-plain.ts
- driver-portal/src/ClientApp/src/app/shared/api/models.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/callback-call-status.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/callback-topic.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/callback.ts
- driver-portal/src/ClientApp/src/app/shared/api/services.ts
- driver-portal/src/ClientApp/src/app/shared/api/services/callback.service.ts
- driver-portal/src/ClientApp/src/app/shared/services/case-management/case-management.service.ts
- Added Backend API for callback request
- Added cancel callback Dialog component
- Added cancel call back UI on the dialog
> DFTDP # 118  UI Development for Driver Request Call back page

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/UserService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/UserManager.cs
- driver-portal/src/ClientApp/src/app/account/account.component.ts
- driver-portal/src/ClientApp/src/app/case-definations/decision-outcome/decision-outcome.component.html
- driver-portal/src/ClientApp/src/app/case-definations/submission-type/submission-type.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/shared/api/fn/profile/api-profile-register-put-json.ts
- driver-portal/src/ClientApp/src/app/shared/api/fn/profile/api-profile-register-put-plain.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/user-registration.ts
- driver-portal/src/ClientApp/src/app/shared/api/services/profile.service.ts
- driver-portal/src/Controllers/ProfileController.cs
- driver-portal/src/Model/UserClaimTypes.cs
- driver-portal/src/Services/UserService.cs
- driver-portal/src/ViewModels/UserRegistration.cs
- Updated user registration flow for account creation
- Updated backend API for user registration
- Updated case definitions
> DFTHG# 66 Account Creation

- driver-portal/src/ClientApp/src/app/case-definations/letter-topic/letter-topic.component.html
- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.scss
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/IcbcController.cs
- shared-portal-ui/projects/core-ui/src/lib/layout/footer/footer.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/footer/footer.component.scss
- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
DFTHG # 847 Driver portal - FAQ topics and information
- Added Help portal content and adjustments to call back styles
DFTHG # 848 Driver portal - site copy review
- Added help content to the footer
- Adjusted styles on cards
> DFTHG # 847 Driver portal - FAQ topics and information

- bcmail-adapter/src/Rsbc.Dmf.BcMailAdapter/Controllers/DocumentsController.cs
- driver-portal/src/ClientApp/src/app/account/account.component.html
- driver-portal/src/ClientApp/src/app/account/account.component.ts
- driver-portal/src/ClientApp/src/app/case-definations/letter-topic/letter-topic.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- landing-page/src/html/DriverPortalLandingPage.html
DFTHG # 845 Landing page - text and links
- Updated landing page with new updates provided by business
- Updated create call back confirmation message
- Updated auto refreshing of dashboard after registration
- Updated Letter topics definitions
DFTHG # 946 Documents that got split are getting classified wrongly and visible on the "DPS General" Queue
Added missing document type code while splitting the documents
> DFTHG # 845 Landing page - text and links

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
Updated Logic to check for manual pass
Added logic to check the driver master status is deceased and stop retrying medical disposition
> DFTHG # 857 Medical Disposition Update - Changes for Manual Pass

- driver-portal/src/ClientApp/src/app/account/account.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- Fixed the issues with call back to request only one when there is a open request
- Fixed minor changes from the feedback
> DFTDP # 174 Summary of Issues with Driver Portal

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Callback/CallbackManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Readme.md
- driver-portal/src/Controllers/DocumentController.cs
- driver-portal/src/Controllers/DriverController.cs
- driver-portal/src/Model/DocumentFactory.cs
- driver-portal/src/ViewModels/Document.cs
I was not able to test the submittal type changes, since I don't know how to get those values. This is very low risk though
> DFTDP-175 adjustments to document upload

- oauth-server/src/OAuthServer/Startup.cs
This is untested but I did build and run the oauth-server and the risk is minimal
> DFTDP-74 add driver license number claim to oauth server

- driver-portal/src/ClientApp/src/app/account/account.component.ts
- driver-portal/src/ClientApp/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/document.ts
- driver-portal/src/ClientApp/src/app/shared/services/login.service.ts
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- landing-page/src/html/DriverPortalLandingPage.html
- Remove  DOCX and added JPEG document type from Submission Requirement page.
- Fixed issue with navigation bar disappearing
- Fixed issue with creating multiple call backs, upload documents
- Fixed landing page astatic changes
- Added letter subtypes to Letters and submission History
> DFTDP # 174 Summary of Issues with Driver Porta

- driver-portal/src/ClientApp/src/app/account/account.component.html
- driver-portal/src/ClientApp/src/app/account/account.component.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/user-profile.ts
- Added email update to profile page
- Added email validations
> DFTDP # 70 Account Creation - Update Email Address

- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
Reset form fields on upload and get Assistance
> DFTDP174 Reset form fields on upload and getAssistance

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
User has  to refresh page before requesting another callback after cancelling.
Mobile view : Get assistance page Call back request section is not getting displayed in properly.
Added reject status to the document status
Added Submission Requirements nav bar
> DFTDP # 174  Summary of Issues with Driver Portal

- driver-portal/src/Configuration.cs
- driver-portal/src/Controllers/DriverController.cs
- driver-portal/src/Program.cs
- driver-portal/src/driver-portal.csproj
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/DriverHistoryController.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Protos/icbcAdapter.proto
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Pssg.Dmf.IcbcAdapter.csproj
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Services/IcbcAdapterService.cs
- icbc-adapter/src/Pssg.Interfaces.Icbc/Helpers/AddressHelper.cs
- icbc-adapter/src/Pssg.Unit.Tests.Interfaces.Icbc/IcbcInterfaceTest.cs
Added icbc get address service to driver-portal
Removed document storage grpc from icbc, since it was not used and was causing issues with driver-portal
> DFTDP-74 icbc address service

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/UserManager.cs
- driver-portal/src/Controllers/ProfileController.cs
- driver-portal/src/Services/UserService.cs
- driver-portal/src/ViewModels/Callback.cs
fix email claim being empty
add preferred time and phone to get callbacks service
fix display name on user registration
update email claim after updating account or user registration
add driver policy authorization check to update driver service
> FIX email claim and get callbacks service

- driver-portal/src/ClientApp/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.html
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/shared/api/models/callback-2.ts
Fixed the description feild on the call backs
- Fixed the error messages on cancel call backs
> DFTDP # 176 Summary of Issues with Driver Portal

- driver-portal/src/Configuration.cs
- driver-portal/src/Program.cs
NOTE this will only work if OpenShift captures console logs, which I think it does but haven't verified
> LOGS add logs for icbc-adapter get token

- medical-practitioner-portal/src/app/Layout/header/header.component.html
- medical-practitioner-portal/src/app/Layout/header/header.component.ts
- medical-practitioner-portal/src/app/account/account.component.html
- medical-practitioner-portal/src/app/account/account.component.scss
- medical-practitioner-portal/src/app/account/account.component.spec.ts
- medical-practitioner-portal/src/app/account/account.component.ts
- medical-practitioner-portal/src/app/app.routes.ts
- Added component for account page 
- Added navigation from the header to account page
- Added UI to show the profile and PIDP endorsements
> DFTDP # 147 Login to Medical Practitioner Portal Account

- medical-practitioner-portal/src/app/account/account.component.html
- medical-practitioner-portal/src/app/app.routes.ts
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/app/get-help/get-help.component.html
- medical-practitioner-portal/src/app/get-help/get-help.component.scss
- medical-practitioner-portal/src/app/get-help/get-help.component.spec.ts
- medical-practitioner-portal/src/app/get-help/get-help.component.ts
- medical-practitioner-portal/src/styles.scss
- Added Get help component
- Added navigation to get help from the dashboard
- Added UI for get help page
> Dmf medical practitioner portal

- driver-portal/src/ClientApp/src/app/case-details/case-details.component.html
- driver-portal/src/ClientApp/src/app/case-details/case-details.component.ts
- driver-portal/src/ClientApp/src/app/case/case.component.html
- driver-portal/src/ClientApp/src/app/case/case.component.ts
- driver-portal/src/ClientApp/src/app/letter-details/letter-details.component.html
- driver-portal/src/ClientApp/src/app/letter-details/letter-details.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.html
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.scss
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.html
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
- Added No records validation to all the results when there are no records for that case
- Updated the case status from card to Accordion
- Updated navigation bar sequence
> DFTDP # 180 UAT Feedback updates

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/DocumentConvertUtil.cs
- Reverting the change back for documentconvertutils.cs to remove the error handling to download the page.
> DFTHG# 912 Tiff Letter Out Not Opening

- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- medical-practitioner-portal/src/app/case-details/case-details.component.html
- medical-practitioner-portal/src/app/case-details/case-details.component.ts
- shared-portal-ui/projects/core-ui/src/public-api.ts
Update the consent message when the documents are upload on submissions tab.
> DFTDP # 180 UAT feedback for driver portal

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- Added new function for calculating dps upload date
- Updated Non comply method to use the new DPS calculation criteria
> DFTHG # 977 Document Requirements Expiring Based on Calendar Date

- legacy-adapter/src/Rsbc.Dmf.LegacyAdapter/Controllers/CasesController.cs
- legacy-adapter/src/Rsbc.Unit.Tests.Dmf.LegacyAdapter/CaseTest.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ProfileController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Properties/launchSettings.json
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
- medical-practitioner-portal/Caddyfile
- medical-practitioner-portal/package-lock.json
This is all that is needed along with Keycloak configuration settings to have Keycloak working with OneHealth on medical portal locally. This will give us a working baseline and then we can add back policies.
> DFTDP-192 disable authorization policies

- .github/workflows/ci-medical-portal-ui.yml
> remove lint

- .github/workflows/ci-medical-portal-ui.yml
> adjust shared folder

- driver-portal/src/ClientApp/src/app/dashboard/dashboard.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.scss
- shared-portal-ui/package-lock.json
- shared-portal-ui/package.json
Bump ejs from 3.1.9 to 3.1.10 in /shared-portal-ui
**- [ ] Version change**
> DFTDP # 203 - Upgrade shared library

- .github/workflows/ci-medical-portal-ui.yml
- medical-practitioner-portal/angular.json
- medical-practitioner-portal/karma.conf.js
- medical-practitioner-portal/package-lock.json
- medical-practitioner-portal/package.json
_DFTDP-215
Update pipeline to build new medical portal instead of old
Fix karma testing on pipeline
Fix docker build image on pipeline
Commented out unit test runner since not all tests pass, currently_
_Test by running workflow on Github manually_
> DFTDP-215 Setup CI for medical portal

- medical-practitioner-portal/angular.json
_DFTDP-209_
_Reproduced and fixed locally by using `--configuration production`_
> DFTDP-209 fix base api url

- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-case-id-get-json.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-case-id-get-plain.ts
- medical-practitioner-portal/src/app/shared/api/models.ts
- medical-practitioner-portal/src/app/shared/api/models/patient-case.ts
- medical-practitioner-portal/src/app/shared/api/models/problem-details.ts
- medical-practitioner-portal/src/app/shared/api/services/cases.service.ts
- DFTDP#151 Medical Practitioner Portal Dashboard
- [x ] No
- [ x] No
- [x ] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [ x] I have performed a self-review of my own code
> DFTDP#151 Medical Practitioner Portal Dashboard

- medical-practitioner-portal/src/app/get-help/get-help.component.html
- medical-practitioner-portal/src/app/get-help/get-help.component.scss
- medical-practitioner-portal/src/assets/images/u84.svg
DFTDP # 144 Medical Practitioner Portal - Help Page
- Added Image to help page
- Updated styles on the help page
- [ X] New feature (non-breaking change which adds functionality)
- [ X] No
- [X ] No
> DFTDP # 144 Medical Practitioner Portal - Help Page

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/DpsAddDocumentTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/IDocumentManager.cs
- [X ] Bug fix (non-breaking change which fixes an issue)
local tests with swagger
- [X ] No
> DFTHG-984 fix for duplicate dmer requirements

- medical-practitioner-portal/src/app/case-details/case-details.component.scss
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.scss
- Updated styles on dashboard and case details to be compatible with tablet
DFTDP # 138 Medical Practitioner Portal - Screen Presentation
Updated styles on dashboard and case details to be compatible with tablet
- [ X] New feature (non-breaking change which adds functionality)
- [X ] No
- [X ] No
- [X ] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [X ] I have performed a self-review of my own …
> DFTDP # 138 Medical Practitioner Portal - Screen Presentation

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Controllers/FileController.cs
> DFTHG-912 - add convert flag for download / preview

- driver-portal/src/ClientApp/src/app/account/account.component.html
- driver-portal/src/ClientApp/src/app/account/account.component.scss
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.scss
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.html
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.scss
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.scss
- driver-portal/src/ClientApp/src/app/user-registration/user-registration.component.html
- driver-portal/src/ClientApp/src/app/user-registration/user-registration.component.scss
- driver-portal/src/ClientApp/src/styles.scss
- Fixed the accessibility issue with buttons on all pages
- Moved button styles to styles.css
- Changed the background color for the disabled fields
- [ X] Refactoring / Documentation
- [X ] No
- [ X] No
- [ X] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [ X] I have performed a …
> DFTDP # 217 Fix the Accessibility review error

- medical-practitioner-portal/src/app/Layout/nav-menu/nav-menu.component.html
- medical-practitioner-portal/src/app/account/account.component.html
- medical-practitioner-portal/src/app/account/account.component.ts
- medical-practitioner-portal/src/app/app.routes.ts
- medical-practitioner-portal/src/app/case-details/case-details.component.scss
- medical-practitioner-portal/src/app/case-details/case-details.component.ts
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.scss
- medical-practitioner-portal/src/case-submissions/case-submissions.component.html
- medical-practitioner-portal/src/case-submissions/case-submissions.component.scss
- medical-practitioner-portal/src/case-submissions/case-submissions.component.spec.ts
- medical-practitioner-portal/src/case-submissions/case-submissions.component.ts
- medical-practitioner-portal/src/quick-links/quick-links.component.html
- medical-practitioner-portal/src/quick-links/quick-links.component.scss
- medical-practitioner-portal/src/quick-links/quick-links.component.spec.ts
- medical-practitioner-portal/src/quick-links/quick-links.component.ts
- medical-practitioner-portal/src/styles.scss
- Updated styles on the filter section on dashboard
Updated button on the medical portal for to be compatible accessibility
- Added case submissions component
- Added quick links component
- Added case submissions card 
- Updated app routes.ts 
- [ X] New feature (non-breaking change which adds functionality)
- [ X] No
- [ X] No
- [ X] My code follows the [style …
> DFTDP # 156 Medical Practitioner Portal - eDMER Status Tracking

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
Tested local still works, will have to see after merged if it fixes Dev
> BUG fix for Dev cms secret

- driver-portal/src/ClientApp/src/app/account/account.component.ts
- shared-portal-ui/projects/core-ui/src/lib/upload-document/upload-document.component.html
- shared-portal-ui/projects/core-ui/src/lib/upload-document/upload-document.component.ts
Added a error message if ICBC is unable to retrieve Address 
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] No
- [X ] No
> Added a error message if ICBC is unable to retrieve Address 

- medical-portal/src/UI/medical-portal/src/app/app.component.ts
- medical-practitioner-portal/src/app/app.model.ts
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.scss
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/seed-data/seed-data.ts
- medical-practitioner-portal/src/styles.scss
- Added search and fileter by status functionality for the list of DMER's on dashboard
- Updated the styles on the DMER's List
- [X ] No
- [X ] No
- [X ] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [ X] I have performed a self-review of my own code
> DFTDP # 151 Medical Practitioner Portal Dashboard

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Auth/AuthConstant.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/MedicalPortalConfiguration.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/RSBC.DMF.MedicalPortal.API.csproj
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/UserService.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/appsettings.json
> DMFTDP-225 add backend keycloak auth

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/UserService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/UserManager.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/UserService.cs
> DMFTDP-192 save loginIds claim

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/UserService.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Auth/AuthConstant.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/AutoMapper.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/UserService.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
- medical-practitioner-portal/src/app/app.component.ts
- medical-practitioner-portal/src/app/app.config.ts
- medical-practitioner-portal/src/environments/environment.prod.ts
DMFTDP-221
Tested with user PIDP00001
> DMFTDP-221 add practitioner and enrolled user role validation on BE

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Unit/AutoMapperTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CaseMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/ICaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/CaseDetail.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/Dto/Case.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/CasesController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/PatientCase.cs
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.scss
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-id-code-get-json.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-id-code-get-plain.ts
- medical-practitioner-portal/src/app/shared/api/models/patient-case.ts
- medical-practitioner-portal/src/app/shared/api/services/cases.service.ts
- Added backend API for search by case number
- Added new GRPC call for searchbyIdCode
- Integrated the APi with front end
- Adjusted the case detail auto mapper
- Added unit tests for GetCaseByIdCode
- [X ] No
- [X ] No
> DFTDP # 194 Implement Backend API call for search results

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CaseMapper.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/CasesController.cs
- medical-practitioner-portal/src/app/case-details/case-details.component.html
- medical-practitioner-portal/src/app/case-details/case-details.component.ts
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.scss
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-case-id-get-json.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-case-id-get-plain.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-search-id-code-get-json.ts
- medical-practitioner-portal/src/app/shared/api/fn/cases/api-cases-search-id-code-get-plain.ts
- medical-practitioner-portal/src/app/shared/api/services/cases.service.ts
DFTDP#222 Create Backend API to get the case details
- Added backend api to get case details
- generated FE services to get the new end point
- Added services to get case details 
- Adjusted styles on dashboard
> DFTDP#222 Create Backend API to get the case details

- driver-portal/src/Controllers/CasesController.cs
DFTDP # 233 Driver Portal Feedback Changes
- Added sorting for the closed cases
- Added the missing document type configuration to openshift environment
- [X ] No
- [X ] No
>  DFTDP # 233 Driver Portal Feedback Changes

- medical-practitioner-portal/package.json
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
This is to test the DEV environment working without the DMER end point
> Removed the end point to remove load  DMER

- medical-practitioner-portal/src/app/app.component.html
- medical-practitioner-portal/src/app/app.component.ts
- medical-practitioner-portal/src/app/app.config.ts
- medical-practitioner-portal/src/app/features/auth/interceptors/bearer-token.interceptor.ts
- medical-practitioner-portal/src/app/features/auth/interceptors/loading.interceptor.ts
DEV comment spinner and add logging to bearer token interceptor
> DEV comment spinner and add logging to bearer token interceptor

- medical-practitioner-portal/src/app/app.component.html
- medical-practitioner-portal/src/app/app.component.ts
- medical-practitioner-portal/src/app/app.config.ts
- medical-practitioner-portal/src/app/features/auth/interceptors/bearer-token.interceptor.ts
- medical-practitioner-portal/src/app/features/auth/interceptors/loading.interceptor.ts
> Revert "DEV comment spinner and add logging to bearer token interceptor"

- medical-practitioner-portal/package-lock.json
- medical-practitioner-portal/package.json
- medical-practitioner-portal/src/app/app.component.html
- medical-practitioner-portal/src/app/case-submissions/case-submissions.component.html
- medical-practitioner-portal/ssl/README.md
> adjust angular

- medical-practitioner-portal/Dockerfile
> adjust Dockerfile

- medical-practitioner-portal/src/app/app.config.ts
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Added authservice to providers and added Mat common module to dashboard

- medical-practitioner-portal/Caddyfile
> adjust Caddyfile

- shared-portal-ui/angular.json
> adjust angular.json

- medical-practitioner-portal/tsconfig.json
> tsConfig changes

- medical-practitioner-portal/tsconfig.json
- shared-portal-ui/projects/core-ui/package.json
> adjust tsconfig.json

- medical-practitioner-portal/src/environments/environment.prod.ts
> adjust environment

- medical-practitioner-portal/src/app/modules/keycloak/keycloak.module.ts
> adjust keycloak config

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/app/modules/keycloak/keycloak.module.ts
> add logging

- medical-practitioner-portal/Caddyfile
> adjust Caddy

- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Commented dashboard to test for DEV environment

- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Enable router link dependacy

- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Added Definitions section on dashboard

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Removed MAtExpansionPanel from providers

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Removed shared definitions from dashboard

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Removed DMER Type Component

- shared-portal-ui/projects/core-ui/src/lib/case-definitions/dmer-status/dmer-status.component.html
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/dmer-status/dmer-status.component.scss
> Testing shared portals

- shared-portal-ui/projects/core-ui/src/lib/case-definitions/dmer-status/dmer-status.component.html
> Testing Shared Portal

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/tsconfig.json
> Added Angular reference in tsconfig

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/dmer-status/dmer-status.component.html
> Enabled DMER status component

- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
> Added DMER Status Component

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
…icate validation
Locally uploading a file
> DEV do not validate document storage adapter certificate

- medical-practitioner-portal/src/app/case-details/case-details.component.html
- medical-practitioner-portal/src/app/case-details/case-details.component.ts
- medical-practitioner-portal/src/app/dashboard/dashboard.component.html
- medical-practitioner-portal/src/app/dashboard/dashboard.component.ts
- medical-practitioner-portal/src/app/definitions/medical-dmer-types/medical-dmer-types.component.html
- medical-practitioner-portal/src/app/definitions/medical-dmer-types/medical-dmer-types.component.scss
- medical-practitioner-portal/src/app/definitions/medical-dmer-types/medical-dmer-types.component.spec.ts
- medical-practitioner-portal/src/app/definitions/medical-dmer-types/medical-dmer-types.component.ts
- medical-practitioner-portal/src/app/submission-requirements/submission-requirements.component.ts
- Added DMER type definitions to medical portal
- Updated shared components references in case details page
> DFTDP # 152 Medical Practitioner Portal - Case Details screen

- medical-practitioner-portal/src/app/case-details/case-details.component.html
- medical-practitioner-portal/src/app/submission-requirements/submission-requirements.component.html
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/case-status/case-status.component.html
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/case-type/case-type.component.html
> Medical Practitioner Portal - Case Details screen

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
> fix config

- medical-practitioner-portal/src/app/Layout/medical-footer/medical-footer.component.html
- medical-practitioner-portal/src/app/Layout/medical-footer/medical-footer.component.ts
- medical-practitioner-portal/src/app/Layout/medical-header/medical-header.component.html
DFTDP # 239 Portal User Interface Changes
- Added Feedback and Get help button navigation on medical portal footer
- Removed the font size increase section from header
- [X ] No
- [X ] No
- [ X] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [ X] I have performed a self-review of my …
>  DFTDP # 239 Portal User Interface Changes

- shared-portal-ui/projects/core-ui/src/lib/layout/footer/footer.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/footer/footer.component.ts
- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/header/header.component.ts
DFTDP # 239 Portal User Interface Changes
- Added Feedback and Get help button navigation on medical portal footer
- Removed the font size increase section from header
- [X ] No
- [X ] No
> DFTDP # 239 Portal User Interface Changes

- pidp-adapter/src/Dockerfile
> fix Dockerfile

- pidp-adapter/src/PidpAdapter.Service/OpenShift.cs
- pidp-adapter/src/PidpAdapter.Service/PidpAdapter.Service.csproj
- pidp-adapter/src/PidpAdapter.Service/Program.cs
> Add OpenShift middleware

- pidp-adapter/src/PidpAdapter.Service/OpenShift.cs
> adjust openshift code

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/RSBC.DMF.MedicalPortal.API.csproj
- medical-portal/src/API/medical-portal.sln
Fix the pidp-adapter client path
> BUG FIX pidp adapter client path

- pidp-adapter/src/PidpAdapter.Service/OpenShift.cs
- pidp-adapter/src/PidpAdapter.Service/Program.cs
> adjust host

- pidp-adapter/src/PidpAdapter.Service/PidpAdapter.Service.csproj
- pidp-adapter/src/PidpAdapter.Service/Startup.cs
> update health checks

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Startup.cs
- medical-practitioner-portal/src/app/denied/denied.component.html
- medical-practitioner-portal/src/app/features/auth/enums/identity-provider.enum.ts
- medical-practitioner-portal/src/app/features/auth/guards/authentication.guard.ts
- medical-practitioner-portal/src/app/features/auth/services/auth.service.ts
DFTDP-146
Locally with users PIDP00001 and PIDP00003
> DFTDP-146 add auth check for enrolled user #1712

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/appsettings.Development.json
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/appsettings.json
Appsetting change needed to fix pidp server url on openshift.
Tested on OpenShift by adding secret to override the wrong appsetting. After confirmed fixed, removed the test secret.
> OPENSHIFT pipd-adapter fix

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ChefsController.cs
> DFTDP-73: Fix missing namespace issue

- medical-practitioner-portal/src/app/Layout/medical-nav-menu/medical-nav-menu.component.html
- medical-practitioner-portal/src/app/Layout/medical-nav-menu/medical-nav-menu.component.scss
> DFTDP-144 style get assistance button to match wireframes

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
DFTHG # 989 ERA and Road Test - ICBC Re-exams Document Requirements Expiring Based on DPSed Processing Date instead of Calendar days
- Fix the dps processing date for ERA results
- Updated logic to check both the paths for dps processing date calculation
> DFTHG # 989 ERA and Road Test - ICBC Re-exams Document Requirements Expiring Based on DPSed Processing Date instead of Calendar days

- driver-portal/src/AutoMapper.cs
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/Tests/Rsbc.Dmf.DriverPortal.Tests.csproj
- driver-portal/src/driver-portal.csproj
DFTDP# 217 Fix the Accessibility review error
- Fixed the accibility error on the upload functionality page.
- Refactored automapper groupsubmittalstatus to use from shared utils
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] No
- [ X] No
> DFTDP# 217 Fix the Accessibility review error

- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/src/app/popup/popup.component.ts
- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.ts
> DFTDP-73: Add start dmer functionality to other pages

- medical-portal/src/UI/src/app/case-details/case-details.component.ts
- medical-portal/src/UI/src/app/case-submissions/case-submissions.component.ts
- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
DFTDP# 156  Medical Practitioner Portal - eDMER Status Tracking
- Added filtering to load only 10 documents on document submission tab.
- Fixed the accessibility issue with drop zone label
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] No
- [ X] No
- [ X] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [ X] I have performed a …
> DFTDP# 156  Medical Practitioner Portal - eDMER Status Tracking

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ChefsController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentTypeController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/RSBC.DMF.MedicalPortal.API.csproj
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/CachedIcbcAdapterClient.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/ChefsBundle.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/Driver.cs
> DFTDP-73: Add icbc adapter and request to get driver details

- medical-portal/src/UI/src/app/case-details/case-details.component.html
- medical-portal/src/UI/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/src/app/case-details/case-details.component.ts
- medical-portal/src/UI/src/app/case-submissions/case-submissions.component.html
- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.ts
- Adjusted the active case details card, -Added lastComplianceDate for submission date
- Added No results card if there are no documents
DFTDP # 157 Medical Practitioner Portal - Start eDMER
- Adjusted the active case details card, 
-Added lastComplianceDate for submission date
- Added No results card if there are no documents 
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] No
- [X ] No
> DFTDP # 157 Medical Practitioner Portal - Start eDMER

- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
> extend timeout

- medical-portal/src/UI/src/app/account/account.component.ts
- medical-portal/src/UI/src/app/features/auth/enums/identity-provider.enum.ts
> DFTDP-251 fix role description by adding a mapping

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Program.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Startup.cs
- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
> adjust limits

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/CasesController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ChefsController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/PatientCase.cs
- medical-portal/src/UI/src/app/shared/api/models/patient-case.ts
DFTDP-227 dmer status mapping and start of dmer type, dmer type will be completed in another PR
Locally with 5 id codes
> DFTDP-227 dmer status mapping

- .github/workflows/cd-partner-portal-api.yml
- .github/workflows/ci-bcmail-adapter.yml
- .github/workflows/ci-cms-adapter.yml
- .github/workflows/ci-medical-portal-api.yml
- .github/workflows/ci-medical-portal-ui.yml
- .github/workflows/ci-migration-metrics-ui.yml
- .github/workflows/ci-partner-portal-api.yml
> update github actions

- .gitignore
> partner portal adjustments

- .github/workflows/ci-partner-portal-api.yml
> adjust github action

- .github/workflows/cd-partner-portal-ui.yml
> add partner cd

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/DynamicsContext.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/src/claim-dmer-popup/claim-dmer-popup.component.html
- medical-portal/src/UI/src/claim-dmer-popup/claim-dmer-popup.component.scss
- medical-portal/src/UI/src/claim-dmer-popup/claim-dmer-popup.component.ts
DFTDP#230 Create a Modal popup to claim and unclaim the DMER when clicks on CLAIM button
- Added unclaim functionality and updated the endpoints
- Updated  Claim/Unclaim modal Modal popup UI and styles
> DFTDP#230 Create a Modal popup to claim and unclaim the DMER when clicks on CLAIM button

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/AutoMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/DocumentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Unit/AutoMapperTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/Dto/Document.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/AutoMapper.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/DmerDocument.cs
- medical-portal/src/UI/src/app/case-submissions/case-submissions.component.scss
- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/src/app/dashboard/dashboard.component.scss
- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/src/app/shared/api/fn/document/api-document-my-dmers-get-json.ts
- medical-portal/src/UI/src/app/shared/api/fn/document/api-document-my-dmers-get-plain.ts
- medical-portal/src/UI/src/app/shared/api/models.ts
- medical-portal/src/UI/src/app/shared/api/models/dmer-document.ts
- medical-portal/src/UI/src/app/shared/api/services/document.service.ts
- medical-portal/src/UI/src/styles.scss
DFTDP # 151 Medical Practitioner Portal Dashboard
- Added DMER Document mapper
- Updated document mapper in case management
- Updated UI end point for  dashboard
- Updated CMS proto
>  DFTDP # 151 Medical Practitioner Portal Dashboard

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/AutoMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/DocumentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/DocumentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/LoginMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/Dto/Login.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/CasesController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/UI/src/app/app.model.ts
- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/src/claim-dmer-popup/claim-dmer-popup.component.scss
DFTDP#156 Medical Practitioner Portal - eDMER Status Tracking
- Adjusted mapping for Actioned Non Comply documents
- Adjusted automapper for mapping Login and practitioner 
- Added Additional logic for Non Comply docuemnts on case and document controller
- Adjusted Dashboard search results to show different buttons based on DMER status
- Added DMER status Enum to app models
> DFTDP#156 Medical Practitioner Portal - eDMER Status Tracking

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
> fix document type issues

- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- Added filter functionality for DMER list
- [ X] No
- [X ] No
> DFTDP# 151 Medical Practitioner Portal Dashboard

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/AutoMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CaseMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/CaseDetail.cs
DFTDP-155 medical conditions (Mihai's PR) part 1 - This PR does nothing! But it also doesn't break anything. This is the first round of changes, these changes in particular add medical conditions to GetCaseDetail which will later be used in medical portal ChefsController GetBundle.
Locally with medical portal and legacy adapter
> DFTDP-155 medical conditions part 1

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/AutoMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CaseService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/DocumentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CaseMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/FlagMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/MedicalConditionMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- driver-portal/src/Controllers/CasesController.cs
DFTDP-155 works towards this ticket but still affectively does nothing, this is to add loading of flags to services needed later to map the flags and medical conditions to chefs forms.
I spent hours regression testing and mapped out all of the affected code. I was not able to test everything and some of my testing touched the code but wasn't a very good test. On the plus side the risk is low and on the off chance we do encounter errors, it should be as easy as fixing a mapping. Below I made a list of all of the affected models and methods and added notes to the ones I tested:
FlagItem proto 
DmerCase proto
SearchReply proto
MarkMedicalUpdatesSent method …
> DFTDP-155 medical conditions (Mihai's PR) part 2 - flags

- medical-portal/src/UI/src/app/account/account.component.ts
DFTDP-251 bug fix for "Undefined" email
Locally with PIDP00006 and PIDP00011
> DFTDP-251 add fix for "Undefined" email

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- medical-portal/src/UI/src/app/case-details/case-details.component.html
- medical-portal/src/UI/src/app/case-details/case-details.component.ts
- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- Fixed the issue with multiple DMER entries for the CASE with different document status
- Added logic to hide Start DMER button on dashboard
- Added logic to show DMER button only if open required DMER is present
> DFTDP # 231 Medical Practitioner Portal - Assign/Claim eDMER

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Properties/launchSettings.json
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/AutoMapper.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ChefsController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/ChefsBundle.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/MedicalCondition.cs
- medical-portal/src/UI/src/assets/chefs/initChefsForm.js
- Adds medical conditions to chefs bundle data
- Imports and loads medical conditions in chefs form
Yes, manually tested.
> DFTDP-73: Add medical conditions to chefs bundle

- medical-portal.sln
- medical-portal/src/API/DMFT.postman_collection.json
- medical-portal/src/API/ReadMe.md
- medical-portal/src/API/medical-portal.sln
add ReadMe.md and Postman service collection
N/A
> REFACTOR add ReadMe.md and Postman service collection

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/DocumentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- medical-portal.sln
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/UserService.cs
- medical-portal/src/API/RSBC.Tests.Unit.DMF.MedicalPortal.API/CustomWebApplicationFactory.cs
- medical-portal/src/API/RSBC.Tests.Unit.DMF.MedicalPortal.API/Integration/DocumentTests.cs
- medical-portal/src/API/RSBC.Tests.Unit.DMF.MedicalPortal.API/RSBC.Tests.Unit.DMF.MedicalPortal.API.csproj
- medical-portal/src/UI/src/app/shared/api/fn/document/api-document-claim-dmer-post-json.ts
- medical-portal/src/UI/src/app/shared/api/fn/document/api-document-claim-dmer-post-plain.ts
- medical-portal/src/UI/src/app/shared/api/fn/document/api-document-unclaim-dmer-post-json.ts
- medical-portal/src/UI/src/app/shared/api/fn/document/api-document-unclaim-dmer-post-plain.ts
- medical-portal/src/UI/src/app/shared/api/services/document.service.ts
- rsbc-dmf.sln
DFTDP-247 integration test for claim and unclaim, refactor claim code to be reused for assigning dmer
Integration tests and claiming and unclaiming DMER H8B2S1
> DFTDP-247 integration test for claim and unclaim

- driver-portal/src/Controllers/CallbackController.cs
- driver-portal/src/Model/CallbackRequest.cs
- driver-portal/src/Tests/Integration/CallbackTests.cs
- driver-portal/src/Tests/Rsbc.Dmf.DriverPortal.Tests.csproj
- partner-portal.sln
- partner-portal/src/partner-portal.sln
Fix callback create controller service, it was using proto model and causing issues with generate API
Locally with integration test
> BUG fix callback create controller service

- partner-portal.sln
- partner-portal/src/UI/src/index.html
- partner-portal/src/partner-portal.sln
> Added Document storage , shared utils to partner portal solution

- partner-portal/src/API/Controllers/DocumentController.cs
- partner-portal/src/API/Controllers/DocumentTypeController.cs
- partner-portal/src/API/Model/DocumentFactory.cs
- partner-portal/src/API/Model/DocumentUtils.cs
- partner-portal/src/API/Program.cs
- partner-portal/src/API/ViewModels/DocumentSubTypes.cs
- partner-portal/src/API/partner-portal.csproj
- partner-portal/src/UI/src/app/shared/api/api.module.ts
- partner-portal/src/UI/src/app/shared/api/fn/document-type/api-document-type-document-sub-type-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/document-type/api-document-type-document-sub-type-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/fn/document/api-document-document-id-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/document/api-document-document-id-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/fn/document/api-document-driver-id-all-documents-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/document/api-document-driver-id-all-documents-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/fn/driver/api-driver-info-driver-licence-number-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/driver/api-driver-info-driver-licence-number-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/models.ts
- partner-portal/src/UI/src/app/shared/api/models/document-sub-types.ts
- partner-portal/src/UI/src/app/shared/api/services.ts
- partner-portal/src/UI/src/app/shared/api/services/document-type.service.ts
- partner-portal/src/UI/src/app/shared/api/services/document.service.ts
- partner-portal/src/UI/src/app/shared/api/services/driver.service.ts
- Added Document controller
- Upload endpoint
- Download endpoint
- Get All documents Endpoint
- Added DocumentType controller
- Added Document Factory , DocumentUtils Models
- Added Document subtype view model
- Added Enum.net, MimeDetect Nuget packages
> DFTDP # 260 Partner Portal - Case Search

- partner-portal/src/API/Dockerfile
Fix cd-partner-portal-api workflow by updating the dockerfile partner portal filepaths
I only test on production
> BUG fix the partner portal project filepaths

- partner-portal/src/API/AutoMapper.cs
- partner-portal/src/API/Controllers/DriverController.cs
- partner-portal/src/API/ViewModels/Driver.cs
- partner-portal/src/UI/src/app/search/search.component.html
- partner-portal/src/UI/src/app/search/search.component.ts
- partner-portal/src/UI/src/app/shared/api/fn/driver/api-driver-info-driver-licence-number-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/driver/api-driver-info-driver-licence-number-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/models/driver.ts
- partner-portal/src/UI/src/app/shared/api/services/driver.service.ts
Driver licence number search
Locally with 05007563
> DFTDP-261 driver licence number search

- partner-portal.sln
Fix cd-partner-portal-api by removing UI project
I only test on production
> BUG remove UI project from VS solution

- partner-portal/src/API/Properties/launchSettings.json
- partner-portal/src/API/partner-portal.csproj
- partner-portal/src/partner-portal.sln
Fix the cd-partner-portal-api by removing the correct UI project and also removing the SPA code in the Api
Locally tested nothing broke
> BUG fix cd partner portal api pipeline

- partner-portal/src/UI/tsconfig.json
> Fix for the ts.config path that causing build errors

- partner-portal/src/UI/angular.json
> Increased angular budget limit to fix the build

- partner-portal/src/UI/package-lock.json
- partner-portal/src/UI/package.json
> Fixed the Dbot security errors on partner portal

- partner-portal/src/UI/src/app/assist-driver/assist-driver.component.html
- partner-portal/src/UI/src/app/assist-driver/assist-driver.component.scss
- partner-portal/src/UI/src/app/assist-driver/assist-driver.component.ts
- partner-portal/src/UI/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.ts
- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.html
- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.ts
- partner-portal/src/UI/src/app/shared/api/models/callback-call-status.ts
- partner-portal/src/UI/src/app/shared/api/models/driver.ts
- partner-portal/src/UI/src/app/shared/api/models/preferred-time.ts
DFTDP # 199 Partner Portal - Get Assistance
- Added Get Assistance Component
- Adjusted to use the callback backend service
- Adjusted Cancel call back component
> DFTDP # 199 Partner Portal - Get Assistance

- driver-portal/src/ClientApp/src/app/app.model.ts
- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- driver-portal/src/ClientApp/src/app/shared/services/user.service.ts
- driver-portal/src/ClientApp/tsconfig.json
- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.ts
- partner-portal/src/UI/src/app/recent-case/recent-case.component.ts
- partner-portal/src/UI/src/app/shared/services/case-management/case-management.service.spec.ts
- partner-portal/src/UI/src/app/shared/services/case-management/case-management.service.ts
- partner-portal/src/UI/src/app/shared/services/user.service.ts
Untested start of DFTDP-269 for get-assistance and recent-case
Locally everything except partner portal get-assistance because it's not completed yet
> DFTDP-269 code consolidation of get assistance and get most recent case

- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.ts
This fixes a bad merge conflict. I must have tested the wrong portal after fixing the merge conflicts in the last PR.
Locally on partner portal get assistance page loads. The callbacks are not completed yet, so it's in it's original state and this will fix the compilation errors.
> BUG fix bad merge conflict

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter.Client/CachedIcbcAdapterClient.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter.Client/Pssg.Dmf.IcbcAdapter.Client.csproj
Simple ICBC feature to skip icbc get history and return a fake user instead [but only in development environment].
Locally without ICBC working, have not tested with ICBC but risk is almost zero since that piece of code has already been tested.
> FEATURE simple icbc feature

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter.Client/CachedIcbcAdapterClient.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter.Client/Pssg.Dmf.IcbcAdapter.Client.csproj
FEATURE remove env check from simple icbc feature flag
> FEATURE remove env check from simple icbc feature flag

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
disable audience check for keycloak to bypass auth failure
Locally reproduced and fixed issue
> BUG disable audience check for keycloak to bypass auth failure

- driver-portal/src/ClientApp/src/app/get-assistance/get-assistance.component.ts
- driver-portal/src/ClientApp/src/app/letters-to-driver/letters-to-driver.component.ts
- driver-portal/src/ClientApp/src/app/recent-case/recent-case.component.ts
- driver-portal/src/ClientApp/src/app/shared/services/case-management/case-management.service.ts
- driver-portal/src/ClientApp/src/app/submission-history/submission-history.component.ts
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- driver-portal/src/ReadMe.md
- driver-portal/src/driver-portal.sln
- partner-portal/src/API/Controllers/DocumentController.cs
- partner-portal/src/API/Controllers/DriverController.cs
- partner-portal/src/API/Program.cs
- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.ts
- partner-portal/src/UI/src/app/letters-to-driver/letters-to-driver.component.ts
- partner-portal/src/UI/src/app/recent-case/recent-case.component.ts
- partner-portal/src/UI/src/app/shared/api/fn/driver/api-driver-all-documents-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/driver/api-driver-all-documents-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/services/document.service.ts
- partner-portal/src/UI/src/app/shared/api/services/driver.service.ts
- partner-portal/src/UI/src/app/shared/services/case-management/case-management.service.ts
- partner-portal/src/UI/src/app/submission-history/submission-history.component.ts
- partner-portal/src/UI/src/app/submission-requirements/submission-requirements.component.ts
DFP-269 completed, a fix for keycloak auth audience, and removing userService from two components
Locally on all affected pages on both portals
> DFP-269 consolidate submission history, and submission requirements

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
Sorry, small cleanup I noticed, moving too fast and missed this with the last PR. No affect, just code cleanup.
> REFACTOR cleanup my mess

- partner-portal/src/API/Program.cs
- partner-portal/src/API/partner-portal.csproj
HealthCheck for partner portal copied from driver portal
http://localhost:8080/hc/ready
http://localhost:8080/hc/live
> BUG fix OpenShift partner-portal bug by adding HealthCheck

- driver-portal/ReadMe.md
- driver-portal/driver-portal.sln
- medical-portal/ReadMe.md
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Auth/AuthConstant.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Model/Constants.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/UserService.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/Endorsement.cs
- medical-portal/src/UI/src/app/account/account.component.html
- medical-portal/src/UI/src/app/account/account.component.ts
- partner-portal/ReadMe.md
Complete my account endorsements excluding licences, which is in another ticket. The manage button does not do anything but there are no requirements for this button and no clues in the wireframes. Note that endorsement management is done by OneHealth, so the button may no longer be applicable.
Locally with one user with and without endorsements
> DFTDP-251 my account endorsements

- partner-portal/src/UI/src/app/case-search/case-search.component.html
- partner-portal/src/UI/src/app/case-search/case-search.component.scss
- partner-portal/src/UI/src/app/case-search/case-search.component.ts
- partner-portal/src/UI/src/app/driver-search/driver-search.component.html
- partner-portal/src/UI/src/app/driver-search/driver-search.component.scss
- partner-portal/src/UI/src/app/driver-search/driver-search.component.ts
DFDP # 260 Partner Portal - Case Search
- Fixed the mat tabs on the case search tab
- Added comments button to open the modal popup
> DFDP # 260 Partner Portal - Case Search

- scheduler/src/Rsbc.Dmf.Scheduler/Startup.cs
- Updated the time on the hangfire Job for BC mail to run at 2AM .
This is because there are some platform issues reported at the same time the job was scheduled at 7
> DFTDP # 273 PROD Issue: BC mail hangfire Job is failing in production

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/AutoMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/DocumentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/IDocumentManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/UpdateDocumentCommand.cs
- medical-portal/ReadMe.md
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ChefsController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ProfileController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Services/PdfService.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/ChefsBundle.cs
- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/src/app/popup/popup.component.ts
- medical-portal/src/UI/src/app/popup/popup.service.ts
- medical-portal/src/UI/src/app/shared/api/models/user-profile.ts
- medical-portal/src/UI/src/claim-dmer-popup/claim-dmer-popup.component.ts
DFPDP-155 endorsement dropdown list includes logged in user
Reload search results after closing popup
Update DMER status to "Under Review" after submission
Locally with a practitioner
> DFPDP-155 endorsement dropdown list includes logged in user

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Client/ServiceCollectionExtensions.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CommentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Startup.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CommentServiceTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Configuration.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CommentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Comment/CommentManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Comment/CommentModel.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Comment/ICommentManager.cs
- partner-portal/src/API/AutoMapper.cs
- partner-portal/src/API/Controllers/CommentsController.cs
- partner-portal/src/UI/src/app/comments/comments.component.html
- partner-portal/src/UI/src/app/comments/comments.component.ts
- partner-portal/src/UI/src/app/driver-search/driver-search.component.html
- partner-portal/src/UI/src/app/driver-search/driver-search.component.ts
- partner-portal/src/UI/src/app/shared/api/fn/comments/api-comments-get-comments-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/comments/api-comments-get-comments-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/services/comments.service.ts
- partner-portal/src/UI/src/app/shared/services/case-management/case-management.service.ts
- Added the backend API for the get comments
- Generated services on the front end
- wired up the UI with the back end service
> DFTDP # 212 Partner Portal - View Comment

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Services/CommentService.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CommentMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Comment/CommentManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Comment/CommentModel.cs
- partner-portal/src/API/ViewModels/Comment.cs
- partner-portal/src/UI/src/app/app.model.ts
- partner-portal/src/UI/src/app/comments/comments.component.html
- partner-portal/src/UI/src/app/comments/comments.component.ts
- partner-portal/src/UI/src/app/shared/api/models/comment.ts
DFTDT # 212 Partner Portal - View Comment
-Fixed the issue with showing data in comments Model
- Adjusted the comment manager logic to filter by ICBC audience
- Added the origin field to comment modal
- Added filtering on the Ui To filter by system and user
- Adjusted the front end API services
-Added Comment origin enum
- Added origin filed to CMS proto
- Adjusted comments service layer 
> DFTDT # 212 Partner Portal - View Comment

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter.Client/CachedIcbcAdapterClient.cs
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Protos/icbcAdapter.proto
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Services/IcbcAdapterService.cs
- medical-portal/ReadMe.md
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/ChefsController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ServiceCollectionExtensions.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Startup.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/Driver.cs
- medical-portal/src/UI/README.md
- medical-portal/src/UI/package-lock.json
- medical-portal/src/UI/src/app/shared/api/models/chefs-bundle.ts
- medical-portal/src/UI/src/app/shared/api/models/driver.ts
- medical-portal/src/UI/src/app/shared/api/models/user-profile.ts
- medical-portal/src/UI/src/assets/chefs/initChefsForm.js
- medical-portal/src/UI/src/claim-dmer-popup/claim-dmer-popup.component.ts
DFTDP-274 add dmer type to chefs form and fix the licence class by adding the field to icbc adapter service and passing it to chefs form.
Tested locally with chefs form and verified fields are loading
> DFTDP-274 add dmer type and licence class to chefs form

- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/src/app/get-help/get-help.component.html
DFTDP # 267 Functional UI Changes on the "Get Assistance" Page
- Fixed RSBC contact info on the Get Assistance page
DFTDP # 265 Make changes to allow name search accept lower or upper case letters
- Fixed the issue with DMER search to search by both upper and lower case
DFTDP # 263 Changes to "This needs to be submitted by" date
- Hide the submitted by date when DMER is not requested.
> DFTDP # 265 Make changes to allow name search accept lower or upper case letters

- partner-portal/src/UI/src/app/comments/add-comments/add-comments.component.html
- partner-portal/src/UI/src/app/comments/add-comments/add-comments.component.scss
- partner-portal/src/UI/src/app/comments/add-comments/add-comments.component.spec.ts
- partner-portal/src/UI/src/app/comments/add-comments/add-comments.component.ts
- partner-portal/src/UI/src/app/comments/comments.component.html
- partner-portal/src/UI/src/app/comments/comments.component.ts
- partner-portal/src/UI/src/app/driver-search/driver-search.component.ts
- Added new add modal popup component
- Fixed the issue with the SubmissionHistoryComponent on driver search
> DFTDP # 213 Partner Portal - Add New Comment

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
> MER-12 - Change DPS logic to use type 999 rather than add the type

- medical-portal/ReadMe.md
- medical-portal/src/UI/src/assets/chefs/initChefsForm.js
- partner-portal/src/API/Controllers/ConfigController.cs
- partner-portal/src/API/Model/AppConfiguration.cs
- partner-portal/src/API/Program.cs
- partner-portal/src/UI/src/app/app.component.ts
- partner-portal/src/UI/src/app/shared/api/api.module.ts
- partner-portal/src/UI/src/app/shared/api/fn/config/api-config-get-json.ts
- partner-portal/src/UI/src/app/shared/api/fn/config/api-config-get-plain.ts
- partner-portal/src/UI/src/app/shared/api/models.ts
- partner-portal/src/UI/src/app/shared/api/models/app-configuration.ts
- partner-portal/src/UI/src/app/shared/api/models/keycloak-config.ts
- partner-portal/src/UI/src/app/shared/api/models/keycloak-configuration.ts
- partner-portal/src/UI/src/app/shared/api/models/keycloak-init-options.ts
- partner-portal/src/UI/src/app/shared/api/services.ts
- partner-portal/src/UI/src/app/shared/api/services/config.service.ts
- partner-portal/src/UI/src/app/shared/services/configuration.service.ts
DFTDP-193 this is only part of the ticket, to fix the keycloak configuration by adding a config service that is consumed by the frontend. I also snuck in some documentation changes for the previous chefs fix that I forgot.
Locally with multiple services, the session variables, and tested the claims were being parsed correctly from Keycloak.
> DFTDP-193 fix configuration service to get correct keycloak configuration

- .github/workflows/cd-cms-adapter.yml
- cms-adapter/src/Dockerfile
> fix cms build

- cms-adapter/src/cms-adapter.sln
> Added missing sharedutils reference

- partner-portal/src/API/Controllers/CommentsController.cs
- partner-portal/src/UI/src/app/case-search/case-search.component.html
- partner-portal/src/UI/src/app/case-search/case-search.component.scss
- partner-portal/src/UI/src/app/comments/comments.component.html
- partner-portal/src/UI/src/app/driver-search/driver-search.component.html
- partner-portal/src/UI/src/app/driver-search/driver-search.component.scss
- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.html
- partner-portal/src/UI/src/app/get-assistance/get-assistance.component.scss
- partner-portal/src/UI/src/app/letters-to-driver/letters-to-driver.component.html
- partner-portal/src/UI/src/app/search/search.component.html
- partner-portal/src/UI/src/app/search/search.component.scss
- Fixed responsive styles on the case search
- Fixed responsive styles on the driver search
- - Fixed responsive styles on the  search dashboard page
- Fixed the styles on comments
- Fixed the API for comments controller
- Fixed the issue with No letters message when there are no letter out documents
- Fixed styling issue on the get assistance page -
> DFTDP 198 Partner Portal - Screen Presentation

- partner-portal/src/UI/src/app/Layout/partner-portal-nav-menu/partner-portal-nav-menu.component.html
- partner-portal/src/UI/src/app/app.routes.ts
- partner-portal/src/UI/src/app/case-search/case-search.component.html
- partner-portal/src/UI/src/app/case-search/case-search.component.ts
- partner-portal/src/UI/src/app/driver-search/driver-search.component.ts
- partner-portal/src/UI/src/app/recent-case/recent-case.component.html
- partner-portal/src/UI/src/app/recent-case/recent-case.component.ts
- partner-portal/src/UI/src/app/search/search.component.html
- partner-portal/src/UI/src/app/search/search.component.scss
- partner-portal/src/UI/src/app/search/search.component.ts
DFTDP # 210 Partner Portal - Driver Search
- Fixed the issue with the case and driver search to through error when there is invalid dl or case id
- Modified the case search and driver search to pass in ID so that the data will be restored after refreshing the page
- Updated the routes to have the ID
- Added navigation to case details from driver search page
- Fixed the recent case refreshing issue
> DFTDP # 210 Partner Portal - Driver Search

- .github/workflows/ci-driver-portal-ui.yml
- driver-portal/ReadMe.md
- driver-portal/src/ClientApp/README.md
- driver-portal/src/ClientApp/package-lock.json
- driver-portal/src/ClientApp/package.json
- driver-portal/src/ClientApp/tsconfig.json
- medical-portal/ReadMe.md
DFTDP#277 Medical Portal - Angular 18 upgrade
- - Updated shared libraries in the driver portal
- Removed the shared libraries path from ts.config
- Updated readme file how to use the shared libraries.
> DFTDP#277 Medical Portal - Angular 18 upgrade

- partner-portal/src/API/Controllers/CasesController.cs
- partner-portal/src/API/Controllers/DocumentController.cs
- partner-portal/src/API/Model/SearchDriverSession.cs
- partner-portal/src/API/Model/UserClaimType.cs
- partner-portal/src/API/Program.cs
- partner-portal/src/API/Services/UserService.cs
DFTDP-288 add display name claim for use with commenterId
Locally with one user and searching both fields
> DFTDP-288 add display name claim for use with commenterId

- partner-portal/src/API/Controllers/DriverController.cs
- partner-portal/src/API/Rsbc.Dmf.PartnerPortal.Api.Tests/Integration/DriverTests.cs
- partner-portal/src/API/Services/UserService.cs
- partner-portal/src/API/ViewModels/Driver.cs
- partner-portal/src/UI/src/app/remedial/remedial.component.html
- partner-portal/src/UI/src/app/search/search.component.html
- Fix the remedial details page
> DFTDP # 214 Partner Portal - Remedial Details

- partner-portal/src/UI/Dockerfile
Updated Docker file to install and build the shared library
> DFDP#201 Partner Portal - Assist Driver Page

- partner-portal/src/UI/src/app/Layout/partner-portal-footer/partner-portal-footer.component.html
- partner-portal/src/UI/src/app/Layout/partner-portal-footer/partner-portal-footer.component.ts
- partner-portal/src/UI/src/app/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.scss
DFTDP # 197 Partner Portal - User Interface
- Fixed the navigation issue with get help button
- Fixed styling issues on the cancel callback popup
> DFTDP # 197 Partner Portal - User Interface

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Controllers/FileController.cs
- MER-25 Add support for PDF swap
- [X ] No
- [X ] My code follows the [style guidelines](https://justice.gov.bc.ca/wiki/display/JAM/RCC+Style+Guide) of this project
- [X ] I have performed a self-review of my own code
> MER-25 Implementation

- driver-portal/src/ClientApp/src/app/account/account.component.html
- medical-portal/src/UI/package-lock.json
- medical-portal/src/UI/package.json
- medical-portal/src/UI/src/app/case-details/case-details.component.scss
DFTDP # 276 Driver portal - Angular 18 update
- Fixed the issue on the account page
DFTDP # 262 Add the claim and unclaim button to the case details screen
Adjusted styling for DMER buttons on case detail page
> DFTDP # 276 Driver portal - Angular 18 update

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Rsbc.Dmf.CaseManagement.csproj
- medical-portal/src/UI/package-lock.json
- medical-portal/src/UI/package.json
Updated System.Text.Json nuget package  in CMS adapter
Updated rollup library in medical portal 
> Fix Debot security errors

- medical-portal/src/UI/src/app/claim-dmer-popup/claim-dmer-popup.component.ts
only include logged in user if the logged in user is a practitioner
> DFTDP-246 fix bug found when current logged in user is not a practitioner

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/AutoMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CaseMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/SecurityTokenProvider.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/Dto/Case.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
> DFTDP-287 fix dmer list case id links

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Controllers/FileController.cs
> Improvements to pdf switch

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/CaseDocument.cs
- medical-portal/src/UI/src/app/case-details/case-details.component.scss
- medical-portal/src/UI/src/app/shared/api/models/case-document.ts
- partner-portal/src/API/Controllers/DriverController.cs
- partner-portal/src/API/ViewModels/Document.cs
- partner-portal/src/UI/src/app/shared/api/models/document.ts
DFTDP # 1010 Feedback: Portal Integration (R3) - Add Audience Flag to Document Requirements- Partner portal
- Added documentmanagerclient to driver controller 
- Added showportalsflag to the document model
-Generated front end api call
> DFTDP # 1010 Feedback: Portal Integration (R3) - Add Audience Flag to Document Requirements- Partner portal

- medical-portal/ReadMe.md
- medical-portal/src/API/Dockerfile
- medical-portal/src/UI/src/assets/chefs/initChefsForm.js
update docker file to install dependencies needed for wkhtmltopdf on OpenShift. Tested locally with docker
> BUG update docker file to install dependencies needed for wkhtmltopdf

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CaseMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Model/CaseDetail.cs
- driver-portal/src/ClientApp/src/app/shared/api/models/case-detail.ts
- driver-portal/src/ViewModels/CaseDetail.cs
- partner-portal/src/API/Controllers/CasesController.cs
- partner-portal/src/API/ViewModels/CaseDetail.cs
- partner-portal/src/UI/src/app/shared/api/models/case-detail.ts
- shared-portal-ui/projects/core-ui/src/lib/recent-case/recent-case.component.html
- shared-portal-ui/projects/core-ui/src/lib/recent-case/recent-case.component.ts
DFTHG # 1009 Feedback: Portal Integration (R3) - Add Case Flag for Show on Portals
- Added showonportals field to case detail models, CMS proto files
- Updated Getmostrecentcase method to include showonportals flag
- Added unit tests for testing Getmostrecentcase method
- Updated FE services with new field
- Updated most recent case to handle the scenario with no active cases
> DFTHG # 1009 Feedback: Portal Integration (R3) - Add Case Flag for Show on Portals - Driver portal

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
DFTHG # 1001 Logic issue in Medical Disposition Update needs correction.
- Fixed the logic for medical disposition pass and adjudication scenarios
> DFTHG # 1001 Logic issue in Medical Disposition Update needs correction.

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Integration/CaseManagerTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
MER # 32 Cases Failing to Close after Case Resolve Date is Passed
- Updated the logic for ResolveCaseStatusUpdates after testing
> MER # 32 Cases Failing to Close after Case Resolve Date is Passed

- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/AutoMapper.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/Controllers/DocumentController.cs
- medical-portal/src/API/RSBC.DMF.MedicalPortal.API/ViewModels/DmerDocument.cs
- medical-portal/src/UI/src/app/dashboard/dashboard.component.html
- medical-portal/src/UI/src/app/dashboard/dashboard.component.ts
- medical-portal/src/UI/src/app/shared/api/models/dmer-document.ts
DFTDP # 227 DMER types mapping between medical portal and dynamics
- Added logged in user Dmer document.
- Updated Document controller
- Updated document auto mapper
- Updated the front end api services 
- Adjusted the logic on the dashboard html to add the new logged in username}
> DFTDP # 227 DMER types mapping between medical portal and dynamics

- .github/workflows/ci-medical-portal-ui.yml
- driver-portal/src/ClientApp/package.json
- medical-portal/src/UI/package.json
- partner-portal/src/UI/package.json
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/eligible-license-class/eligible-license-class.component.ts
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/letter-topic/letter-topic.component.ts
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/rsbc-case-assignment/rsbc-case-assignment.component.ts
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/submission-status/submission-status.component.ts
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/submission-type/submission-type.component.ts
DFTDP # 292 Cleanup frontend and devop items
- Fixed the gen api command in driver portal package.json
- Fixed the css files to scss files for definition components
- add test runner on medical portal CI-
> DFTDP # 292 Cleanup frontend and devop items

- partner-portal/src/UI/src/app/case-search/case-search.component.html
- partner-portal/src/UI/src/app/case-search/case-search.component.ts
- shared-portal-ui/projects/core-ui/src/lib/app.model.ts
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.html
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.ts
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.ts
DFTHG # 283 Move submission-requirements to shared library
Added the api config url for uplaod endpoint to get the correct base url
-  Added api config as an input parameter to get the correct base url
> DFTHG # 283 Move submission-requirements to shared library

- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/Controllers/IcbcController.cs
DFTHG # 1019 REQUEST Microsoft Premium Support to assist us with the  DFTHG-969 No Timeline on Case Record issue
- Added time delay on the create candidate controller method to prevent the time line issue for larger batches.
> DFTHG # 1019 REQUEST Microsoft Premium Support to assist us with the  DFTHG-969 No Timeline on Case Record issue

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/DocumentManager.cs
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.ts
Added Console to test the validation error on DEV.
Reverted logic for portal flag
> DFTDP # 276 : Angular 18 update - Phone number validation

- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
- partner-portal/src/UI/src/app/get-help/get-help.component.html
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/decision-outcome/decision-outcome.component.html
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/dmer-type/dmer-type.component.html
- shared-portal-ui/projects/core-ui/src/lib/case-definitions/submission-status/submission-status.component.html
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.html
- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
- shared-portal-ui/projects/core-ui/src/lib/submission-history/submission-history.component.html
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.html
DFTDP # 304 - Fixed the working on get assistance introduction
DFTDP # 294 Letters to Driver -Added period
DFTDP # 295 Get assistance page grammar correction
DFTDP # 296- Help topics- Fixed grammar on received incorrect letter help card
DFTDP # 298 - Fixed help topics grammar on request extension card
DFTDP # 302 - Fixed wordings on the file upload section
Fixed the definitions on 
DFTDP # 299 Definitions / Decision Outcome Tab / Non Comply
DFTDP# 297 Definitions / DMER Type
DFTDP # 301 Definitions / Submission Status / Open Required
DFTDP # 300 Definitions / Decision Outcome Tab / Voluntary Surrender
DFTDP # 303 Submission History - Fixed wording on history page
if your change is a breaking change, please add `breaking change` label to …
> DFTDP # 293 Driver Portal: SPELLING, GRAMMAR AND SENTENCE FORMAT

- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/CaseManager.cs
- driver-portal/src/ClientApp/src/app/definitions/definitions.component.html
- driver-portal/src/ClientApp/src/app/definitions/definitions.component.ts
- icbc-adapter/src/Pssg.Dmf.IcbcAdapter/EnhancedIcbcApiUtils.cs
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.html
_ fixed the case status and ;etter topics definitions
- Fixed help topics on get assstance page
> DFTDP # 309 Definitions

- landing-page/src/html/index.html
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
- Fixed the language on the landing page
- Added an introduction tab on the driverportal menu
> DFTDP# 326 Driver Portal Landing Page / Introduction screen

- cms-adapter/src/Rsbc.Dmf.CaseManagement.Service/Protos/cmsAdapter.proto
- cms-adapter/src/Rsbc.Dmf.CaseManagement.Tests/Unit/AutoMapperTests.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Dynamics/Mapper/CallbackMapper.cs
- cms-adapter/src/Rsbc.Dmf.CaseManagement/Manager/Callback/CallbackModel.cs
- driver-portal/src/AutoMapper.cs
- driver-portal/src/Controllers/CallbackController.cs
- driver-portal/src/Model/CallbackRequest.cs
- driver-portal/src/Tests/Integration/CallbackTests.cs
- driver-portal/src/Tests/Unit/AutoMapperTests.cs
- driver-portal/src/ViewModels/Callback.cs
- shared-portal-ui/projects/core-ui/src/lib/api/models/callback.ts
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.html
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/cancel-callback-dialog/cancel-callback-dialog.component.ts
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.html
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.scss
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.ts
DFTDP # 322 Driver Portal / Request Call Back / Screen visible to driver after clicking new tile ‘Request Call Back’.
- Added UI for the request call back feature
- Added validations for the description text area
- Remove the required phone and subject required fields.
- Hiding the call back buttons on all the other tiles
- Added new description field to the models and auto mappers and unit tests
- updated FE logic to set the description field
- Adjusted the logic on the get call backs to get the description field
- Adjusted UI to get the new description field
Include screen captures or …
> DFTDP # 322 Driver Portal / Request Call Back / Screen visible to driver after clicking new tile ‘Request Call Back’.

- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.html
- Fixed the Note to go to the next line on file upload
> DFTDP # 302 Submission Requirements / Upload File

- .gitignore
- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Controllers/FileController.cs
- document-storage-adapter/src/Pssg.Interfaces.S3/S3.cs
- document-storage-adapter/src/Pssg.Unit.Tests.Interfaces.S3/DynamicsInterfaceTest.cs
> MER-25 - improvements to file download

- landing-page/src/html/index.html
- shared-portal-ui/projects/core-ui/src/lib/layout/nav-menu/nav-menu.component.html
DFTDP # 326 Driver Portal Landing Page / Introduction screen
- Added Driver portal login button the landing page
- Updated styles on the get assistance section
- Removed the introduction tab from the driver portal menu
>  DFTDP # 326 Driver Portal Landing Page / Introduction screen

- .github/workflows/cd-driver-portal-ui-prodtest.yml
- driver-portal/src/ClientApp/Dockerfile.ProdTest
> Fixed the docker and github cd pipeline for driver portal prod test

- driver-portal/src/ClientApp/src/app/definitions/definitions.component.html
DFTDP # 309 Driver Portal / Definitions
- Fixed the decision outcome in definitions
> DFTDP # 309 Driver Portal / Definitions - Fixed the decision outcome in definitions

- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.html
- driver-portal/src/ClientApp/src/app/submission-requirements/submission-requirements.component.ts
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.scss
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.ts
> Updated the api url for the upload documents

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Startup.cs
> add base path

- document-storage-adapter/src/Pssg.DocumentStorageAdapter/Startup.cs
- medical-portal/src/UI/src/app/shared/api/fn/config/api-config-get.ts
- medical-portal/src/UI/src/seed-data/seed-data.ts
> adjust pathbase

- shared-portal-ui/projects/core-ui/src/lib/submission-history/submission-history.component.html
DFTDP # 331 Driver Portal / Submission History Tab
- Fixed the spelling on the submission history tab
> DFTDP # 331 Driver Portal / Submission History Tab

- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
- shared-portal-ui/projects/core-ui/src/lib/submission-history/submission-history.component.html
DFTDP #332 
- Added 'Get Assistance' Link to Letter To Driver and Submission History pages
Manual Testing
> Add 'Get Assistance' to Letter To Driver and Submission History pages

- driver-portal/src/ClientApp/src/app/account/account.component.html
> ICBC - update your address information link change

- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
- partner-portal/src/UI/src/app/get-help/get-help.component.html
- shared-portal-ui/projects/core-ui/src/lib/get-assistance/get-assistance.component.html
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.html
- shared-portal-ui/projects/core-ui/src/lib/upload-document/upload-document.component.html
- DFTDP-337, DAD-290
Manual Testing
> ICBC - Content update

- medical-portal/src/UI/src/app/Layout/medical-footer/medical-footer.component.html
- partner-portal/src/UI/src/app/Layout/partner-portal-footer/partner-portal-footer.component.html
- shared-portal-ui/projects/core-ui/src/lib/layout/footer/footer.component.html
> Feedback button target url update

- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.html
- shared-portal-ui/projects/core-ui/src/lib/upload-document/upload-document.component.html
> dmf-340 - Content updated, Download button temporary removed

- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
> Letter to driver text update

- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
> dmf-340 - Download Letter to driver button reverted

- shared-portal-ui/projects/core-ui/src/lib/case-definitions/submission-status/submission-status.component.html
> DFTDP-314 - Driver Portal / Definitions / Submission Status

- driver-portal/src/ClientApp/src/app/shared/api/models/document.ts
- driver-portal/src/Controllers/DocumentController.cs
- driver-portal/src/Controllers/DriverController.cs
- driver-portal/src/Model/DocumentUtils.cs
- driver-portal/src/ViewModels/Document.cs
- driver-portal/src/driver-portal.csproj
- partner-portal/src/UI/src/app/shared/api/models/document.ts
- shared-portal-ui/projects/core-ui/src/lib/api/models/document.ts
- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
…
- DFTDP-351 - Adapter to Convert .tiff to PDF in Driver Portal
Manual Testing
> dmf-351 - Letter to Driver tiff files converted to PDF. The error message displayed if the file is corrupted

- partner-portal/src/UI/package-lock.json
- partner-portal/src/UI/package.json
- Spinner library update for the partner portal
Manual testing
> rsbc-dmf-351 - Spinner dependency added to the partner portal

- driver-portal/src/Model/DocumentUtils.cs
- driver-portal/src/driver-portal.csproj
> dmf-351 - SixLabors version update

- medical-portal/src/UI/src/app/submission-requirements/submission-requirements.component.html
- shared-portal-ui/projects/core-ui/src/lib/letters-to-driver/letters-to-driver.component.html
- shared-portal-ui/projects/core-ui/src/lib/submission-requirements/submission-requirements.component.html
- shared-portal-ui/projects/core-ui/src/lib/upload-document/upload-document.component.html
- #dmf-340 Content updated
Manual Test
> dmf-340 - Remove content for 'Coming soon'

- medical-portal/ReadMe.md
- medical-portal/src/UI/src/app/dmer-buttons/dmer-buttons.component.ts
- medical-portal/src/UI/src/app/popup/popup.component.ts
- Fixed the issue with refreshing the serach after submitting the edmr form
DFTDP # 161 eDMER Submission Confirmation
- Added a confirmation popup after submitting the edmr form
Updated readme file how to add endorsements in one health system
> DFTDP # 155 eDMER Form Tool Integration - Form Save / Submit
